rewrite: AU-2032: RewriteAttachmentHandler class
City-of-Helsinki/hel-fi-drupal-grants pull request #1112
Opened 2024-01-12 10:37 UTC by Puavo

# [AU-2032](https://helsinkisolutionoffice.atlassian.net/browse/AU-2032)

Helpota koodin ylläpitoa ja vähennä sonarlintin vinkunaa

## What was done

Uudelleenkirjoitettu luokka sonarlintin valitusten perusteella

## How to install

* Make sure your instance is up and running on correct branch.
  * `git checkout feature/AU-2032-attachmenthanlder-rewrite`
  * `make fresh`
* Run `make drush-cr`

## How to test

* [ ] Check that this feature works
* [ ] Check that code follows our standards

2024-02-29 07:07 UTC, jiisuominen requested changes
> *Warning*: Trying to access array offset on value of type null in *Drupal\grants_attachments\Element\GrantsAttachments::validateUpload()* (line *500* of *modules/custom/grants_attachments/src/Element/GrantsAttachments.php*).


> The website encountered an unexpected error. Please try again later.
> *Error*
> : Call to undefined method Drupal\grants_attachments\AttachmentHandler::getFiletypeFromFieldElement() in
> *Drupal\grants_attachments\AttachmentHandler->parseAttachments()*
> (line *378*
> of
> *modules/custom/grants_attachments/src/AttachmentHandler.php*
> ).


> The website encountered an unexpected error. Please try again later.
> *Error*
> : Class "AttachmentHandlerHelper" not found in
> *grants_handler_preprocess_webform_submission_attachment_list()*
> (line
> *1295*
> of
> *modules/custom/grants_handler/grants_handler.module*
> ).

tollasta herjaa automaatti- ja manuaalitesteissä

2024-03-07 05:35 UTC, jiisuominen commented
@Puavo kun teet muutoksia pullariin, pyydä ihmeessä uus review. nää jää roikkumaan tosi helposti ja kun oot tehny muutoksen niin on vaan helpointa, että siinä samassa sit pyydät uuden reviewn.

2024-03-21 06:23 UTC, jiisuominen requested changes
> // Import the listed configuration changes?: yes.
> 
>  [error]  Drupal\Core\Config\ConfigImporterException: There were errors validating the config synchronization.
> Unable to install the <em class="placeholder">jquery_ui_draggable</em> module since it does not exist. in Drupal\Core\Config\ConfigImporter->validate() (line 794 of /app/public/core/lib/Drupal/Core/Config/ConfigImporter.php).
> 
> In ConfigImportCommands.php line 324:
> 
>   The import failed due to the following reasons:
>   Unable to install the <em class="placeholder">jquery_ui_draggable</em> module since it does not exist.
> 
>

2024-03-21 06:30 UTC, jiisuominen commented
Eiku toi jquery moduliongelma taitaaki olla [tästä ](https://github.com/City-of-Helsinki/hel-fi-drupal-grants/commit/9c6a71d161979484458516d6184e3ecd35b8bad1)autoupdatesta peräisin

2024-04-02 05:28 UTC, jiisuominen requested changes
> TypeError: Drupal\grants_attachments\AttachmentHandler::hasExistingBankAccountConfirmation(): Argument #2 ($selectedAccountConfirmation) must be of type array, null given, called in /app/public/modules/custom/grants_attachments/src/AttachmentHandler.php on line 535 in Drupal\grants_attachments\AttachmentHandler->hasExistingBankAccountConfirmation() (line 683 of modules/custom/grants_attachments/src/AttachmentHandler.php).

![image](https://github.com/City-of-Helsinki/hel-fi-drupal-grants/assets/892920/23fcedd6-cf1e-48d6-95c4-fd5764168c31)

Näyttäs siltä, ettei tota `$selectedAccountConfirmation` oo alustettu lainkaan tossa vaiheessa.

Tässä siis kopioidulle hakemukselle lisäämässä liitteitä. Ilmeisesti kopiointi jotenkin rikki?

Regressiotestit menee läpi, ilmeisesti koska siellä ei kopioida asioita vielä. 

@Alexander-Tallqvist-Siili [täällä ](https://helsinkisolutionoffice.atlassian.net/browse/AU-2048)ratkoo kopiointitestejä kun pääsee sinne..

Mut nyt tähän pitäs tuo ratkasta jollain tavalla.

2024-04-02 13:50 UTC, Puavo commented
Develop mergetty tähän ja bugi korjattu. Testailin lokaalilla kopioimalla muutaman hakemuksen.

2024-04-03 06:51 UTC, jiisuominen commented
testi jee jee @Puavo

2024-04-03 09:21 UTC, jiisuominen commented
> Develop mergetty tähän ja bugi korjattu. Testailin lokaalilla kopioimalla muutaman hakemuksen.

Siis testasitko hakemusten kopiointia klikkaamalla tota nappia?
![image](https://github.com/City-of-Helsinki/hel-fi-drupal-grants/assets/892920/d94d9227-8c0f-45f5-b946-943e347f4d60)

Mulla siis kopioi hakemuksen, mutta tuo dialogi ei katoa ja kun katon logista ni tällasen virheen heittää:

> Error: Class "Drupal\grants_attachments\ApplicationHandler" not found in Drupal\grants_attachments\AttachmentHandlerHelper::addEnvToIntegrationId() (line 105 of /app/public/modules/custom/grants_attachments/src/AttachmentHandlerHelper.php)#0 /app/public/modules/custom/grants_attachments/src/AttachmentHandler.php(844): Drupal\grants_attachments\AttachmentHandlerHelper::addEnvToIntegrationId() #1 /app/public/modules/custom/grants_attachments/src/AttachmentHandler.php(555): Drupal\grants_attachments\AttachmentHandler->addFileArrayToFormData() #2 /app/public/modules/custom/grants_handler/src/ApplicationHandler.php(2413): Drupal\grants_attachments\AttachmentHandler->handleBankAccountConfirmation() #3 /app/public/modules/custom/grants_handler/src/ApplicationHandler.php(1396): Drupal\grants_handler\ApplicationHandler->handleBankAccountCopying() #4 /app/public/modules/custom/grants_handler/src/Form/CopyApplicationModalForm.php(206): Drupal\grants_handler\ApplicationHandler->initApplication() #5 [internal function]: Drupal\grants_handler\Form\CopyApplicationModalForm->submitForm() #6 /app/public/core/lib/Drupal/Core/Form/FormSubmitter.php(114): call_user_func_array() #7 /app/public/core/lib/Drupal/Core/Form/FormSubmitter.php(52): Drupal\Core\Form\FormSubmitter->executeSubmitHandlers() #8 /app/public/core/lib/Drupal/Core/Form/FormBuilder.php(597): Drupal\Core\Form\FormSubmitter->doSubmitForm() #9 /app/public/core/lib/Drupal/Core/Form/FormBuilder.php(325): Drupal\Core\Form\FormBuilder->processForm() #10 /app/public/core/lib/Drupal/Core/Controller/FormController.php(73): Drupal\Core\Form\FormBuilder->buildForm() #11 [internal function]: Drupal\Core\Controller\FormController->getContentResult() #12 /app/public/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(123): call_user_func_array() #13 /app/public/core/lib/Drupal/Core/Render/Renderer.php(580): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() #14 /app/public/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(121): Drupal\Core\Render\Renderer->executeInRenderContext() #15 /app/public/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(97): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext() #16 /app/vendor/symfony/http-kernel/HttpKernel.php(169): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() #17 /app/vendor/symfony/http-kernel/HttpKernel.php(81): Symfony\Component\HttpKernel\HttpKernel->handleRaw() #18 /app/public/core/lib/Drupal/Core/StackMiddleware/Session.php(58): Symfony\Component\HttpKernel\HttpKernel->handle() #19 /app/public/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(48): Drupal\Core\StackMiddleware\Session->handle() #20 /app/public/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(48): Drupal\Core\StackMiddleware\KernelPreHandle->handle() #21 /app/public/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(51): Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle() #22 /app/public/modules/contrib/helfi_helsinki_profiili/src/RegisterPageRedirectMiddleware.php(72): Drupal\Core\StackMiddleware\NegotiationMiddleware->handle() #23 /app/public/modules/contrib/remove_http_headers/src/StackMiddleware/RemoveHttpHeadersMiddleware.php(49): Drupal\helfi_helsinki_profiili\RegisterPageRedirectMiddleware->handle() #24 /app/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Drupal\remove_http_headers\StackMiddleware\RemoveHttpHeadersMiddleware->handle() #25 /app/public/core/lib/Drupal/Core/DrupalKernel.php(718): Stack\StackedHttpKernel->handle() #26 /app/public/index.php(19): Drupal\Core\DrupalKernel->handle() #27 {main}

2024-04-03 09:48 UTC, jiisuominen approved these changes
Näyttäs toimivan.

2024-04-03 09:49 UTC, merged