fix: AU-2055: Handle attachment field properly in Atv schema
City-of-Helsinki/hel-fi-drupal-grants pull request #1218
Opened 2024-03-04 15:09 UTC by Puavo

# [AU-2055](https://helsinkisolutionoffice.atlassian.net/browse/AU-2055)

Käsittele liitteiden metatiedot oikein.

## What was done

* Hae liitekenttien tiedot AttachmentHandler-luokasta jotta metatiedot voidaan hakea webformista
* Päivitä yksikkötestien käyttämä data

## How to install

* Make sure your instance is up and running on correct branch.
  * `git checkout feature/AU-2055-attachment-field-in-atv-schema`
  * `make fresh`
* Run `make drush-cr`

## How to test

* [ ] Aja yksikkötestit readmen ohjeiden mukaisesti

## Designers review

* [x] This PR does not need designers review
* [ ] This PR has been visually reviewed by a designer (Name of the designer)

## Automatic- / Regression tests

* [x] This PR makes no changes that effects any tests. (This will be caught in automatic testing later on, but please, please run regression tests always on PR before asking for a review)
* [x] This PR passes regression tests. (`make test-pw`)

## Other PRs

2024-03-06 06:46 UTC, jiisuominen reviewed
Miks noi 3rd party settingsit on ollu poiskommentoituna tuolla installissa?

2024-03-06 07:53 UTC, Puavo commented
Formien asennus 3rdpartysettingsien kanssa vaatii scheman. Aiemmin noissa atvschema-testeissä ei ole tarvinnut niitä joten oli helpompaa vaan kommentoida ne pois.

2024-03-06 08:17 UTC, jiisuominen commented
@Puavo avaa vielä vähän tän pullarin funktioo. tossa @oskarimysteerio kanssa vähän ihmeteltiin :)

2024-03-06 08:18 UTC, jiisuominen commented
...ja tuolla sonarcloudin herjoissa oli taas jotain jotka sais pois suht pienellä vaivalla... pitäsköhän niitä yrittää vähän täs samalla taas korjata vai jättää omaan täskiinsä?

2024-03-06 10:28 UTC, Puavo commented
Päivitin syyn tähän PR:ään aloitusviestiin.

2024-03-06 12:21 UTC, jiisuominen commented
Musta tää on ok. @Alexander-Tallqvist-Siili jos tsekkaat vielä noi envimuutokset ja mahollisesti tähän samaan hierot loppuun tai sit uudella pullarilla, mulle ei niin väliä.

2024-03-06 13:27 UTC, Alexander-Tallqvist-Siili commented
> Musta tää on ok. @Alexander-Tallqvist-Siili jos tsekkaat vielä noi envimuutokset ja mahollisesti tähän samaan hierot loppuun tai sit uudella pullarilla, mulle ei niin väliä.

@jiisuominen Siivosin tuolti vielä pois turhia juttuja liittyen .test_env -tiedostoon. Jos testit on mennyt läpi, niin kaikki on varmasti OK.

2024-03-07 05:25 UTC, jiisuominen commented
@Puavo kävin nyt assignaamassa sulle ne sonarin herjat jotka tästä vois korjata. mut me myös tarvittais täältä noita muutoksia, niin voisit ehkä suorittaa refaktorointia?

2024-03-07 05:26 UTC, jiisuominen requested changes
Sonarin matalalla roikkuvat asiat vois korjata ennen ku mergetään

2024-03-07 06:52 UTC, Puavo commented
Mä käyn keräilemässä vähän hedelmiä.

2024-03-20 05:48 UTC, jiisuominen commented
@Puavo mites tää?

2024-03-20 09:26 UTC, Puavo commented
Toisessa pullarissa on kasa korjauksia sonarlintin vinkunaan: https://github.com/City-of-Helsinki/hel-fi-drupal-grants/pull/1112

2024-04-08 05:41 UTC, jiisuominen requested changes
> Error: Call to undefined method Drupal\grants_attachments\AttachmentHandler::cleanIntegrationId() in Drupal\grants_attachments\AttachmentHandler->deletePreviousAccountConfirmation() (line 886 of /app/public/modules/custom/grants_attachments/src/AttachmentHandler.php) [5caf96b7-f991-4fce-9ef6-31e665e16bc8]. (HP UUID: 76268b22-7b30-4458-af89-82eae130bd8c)

![image](https://github.com/City-of-Helsinki/hel-fi-drupal-grants/assets/892920/561a7ce6-fcab-4eed-8b71-5f284fce75ad)

2024-04-08 05:44 UTC, jiisuominen commented
🔥 [local] [hel-fi-drupal-grant-applications] /app $ composer phpcs
> vendor/bin/phpcs public/modules/custom --standard=Drupal,DrupalPractice --ignore=*.js,*.css --extensions=php,module,install

FILE: /app/public/modules/custom/grants_industries/src/Access/WebformRestrictedRouteAccessCheck.php
---------------------------------------------------------------------------------------------------
FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
---------------------------------------------------------------------------------------------------
 55 | WARNING | \Drupal calls should be avoided in classes, use dependency injection instead
---------------------------------------------------------------------------------------------------


FILE: /app/public/modules/custom/grants_industries/src/Access/WebformAdminRouteAccessCheck.php
----------------------------------------------------------------------------------------------
FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
----------------------------------------------------------------------------------------------
 55 | WARNING | \Drupal calls should be avoided in classes, use dependency injection instead
----------------------------------------------------------------------------------------------

Time: 19.97 secs; Memory: 32MB

En nyt saa muokattua noita tekstejä, mutta tollasta herjaa phpcs, sitäkin vois tsekkaa ku tekee PR

2024-04-09 11:29 UTC, Puavo commented
Korjailin phpcs:n huolenaiheet sekä mainitun virheen.

2024-04-15 05:24 UTC, jiisuominen approved these changes

2024-04-15 05:25 UTC, merged