feat: AU-2123: Drupal 10 update
City-of-Helsinki/hel-fi-drupal-grants pull request #1241
Opened 2024-03-08 14:08 UTC by Puavo

# [AU-2123](https://helsinkisolutionoffice.atlassian.net/browse/AU-2123)

Päivitä Drupal versioon 10. Tämä on draft-tilassa koska ensin pitää päivittää helfi-moduulit.

## What was done

* This thing was fixed

## How to install

* Make sure your instance is up and running on correct branch.
  * `git checkout feature/AU-2123-drupal-10`

## How to test

* [ ] Check that this feature works
* [ ] Check that code follows our standards

## Designers review

* [x] This PR does not need designers review
* [ ] This PR has been visually reviewed by a designer (Name of the designer)

## Automatic- / Regression tests

* [ ] This PR makes no changes that effects any tests. (This will be caught in automatic testing later on, but please, please run regression tests always on PR before asking for a review)
* [ ] This PR passes regression tests. (`make test-pw`)

## Other PRs

* [Audit log](https://github.com/City-of-Helsinki/drupal-module-helfi-audit-log/pull/12)
* [Helsinki profiili](https://github.com/City-of-Helsinki/drupal-module-helfi-helsinki-profiili/pull/24)

2024-03-13 11:01 UTC, Puavo commented
Tunnetut ongelmat on mainittu kuvauksessa, mutta muilta osin tämä on valmis katselmoitavaksi.

2024-03-14 07:29 UTC, Puavo commented
Dailyssa sovittu että Petri katsoo kuvakeongelmaa. Juho katsoo bäkkärimuutoksia ja Oskari auttaa projektispesifisten bäkkärimuutosten kanssa.

2024-03-18 10:04 UTC, oskarimysteerio commented
Mulla tuoreella (testin 18.3) kannalla tapahtuu seuraavaa:

![image](https://github.com/City-of-Helsinki/hel-fi-drupal-grants/assets/43133397/b90fcfc9-b68f-4c7e-8f33-9cd7600ce49b)

2024-03-20 06:51 UTC, jiisuominen requested changes
> > [error]  SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'en-38' for key 'locales_target.PRIMARY': INSERT INTO "locales_target" ("lid", "language", "translation", "customized") VALUES (:db_insert_placeholder_0, :db_insert_placeholder_1, :db_insert_placeholder_2, :db_insert_placeholder_3); Array
> > (
> >     [:db_insert_placeholder_0] => 38
> >     [:db_insert_placeholder_1] => en
> >     [:db_insert_placeholder_2] => Ylempi sisältöalue
> >     [:db_insert_placeholder_3] => 1
> > )
> >
> >  [error]  Update failed: helfi_base_content_update_9006
> >  [notice] Update started: helfi_ckeditor_update_9008
> >  [notice] filter.format.plain_text rewritten by helfi_ckeditor
> >  [error]  SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'en-38' for key 'locales_target.PRIMARY': INSERT INTO "locales_target" ("lid", "language", "translation", "customized") VALUES (:db_insert_placeholder_0, :db_insert_placeholder_1, :db_insert_placeholder_2, :db_insert_placeholder_3); Array
> > (
> >     [:db_insert_placeholder_0] => 38
> >     [:db_insert_placeholder_1] => en
> >     [:db_insert_placeholder_2] => Ylempi sisältöalue
> >     [:db_insert_placeholder_3] => 1
> > )
> >
> >  [error]  Update failed: helfi_ckeditor_update_9008
> >  [notice] Update started: helfi_node_page_update_9003
> >  [error]  SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'en-38' for key 'locales_target.PRIMARY': INSERT INTO "locales_target" ("lid", "language", "translation", "customized") VALUES (:db_insert_placeholder_0, :db_insert_placeholder_1, :db_insert_placeholder_2, :db_insert_placeholder_3); Array
> > (
> >     [:db_insert_placeholder_0] => 38
> >     [:db_insert_placeholder_1] => en
> >     [:db_insert_placeholder_2] => Ylempi sisältöalue
> >     [:db_insert_placeholder_3] => 1
> > )
> >
> >  [error]  Update failed: helfi_node_page_update_9003
> >  [notice] Update started: helfi_paragraphs_accordion_update_9002
> >  [error]  SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'en-38' for key 'locales_target.PRIMARY': INSERT INTO "locales_target" ("lid", "language", "translation", "customized") VALUES (:db_insert_placeholder_0, :db_insert_placeholder_1, :db_insert_placeholder_2, :db_insert_placeholder_3); Array
> > (
> >     [:db_insert_placeholder_0] => 38
> >     [:db_insert_placeholder_1] => en
> >     [:db_insert_placeholder_2] => Ylempi sisältöalue
> >     [:db_insert_placeholder_3] => 1
> > )
> >
> >  [error]  Update failed: helfi_paragraphs_accordion_update_9002
> >  [notice] Update started: helfi_paragraphs_chart_update_9001
> >  [error]  SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'en-38' for key 'locales_target.PRIMARY': INSERT INTO "locales_target" ("lid", "language", "translation", "customized") VALUES (:db_insert_placeholder_0, :db_insert_placeholder_1, :db_insert_placeholder_2, :db_insert_placeholder_3); Array
> > (
> >     [:db_insert_placeholder_0] => 38
> >     [:db_insert_placeholder_1] => en
> >     [:db_insert_placeholder_2] => Ylempi sisältöalue
> >     [:db_insert_placeholder_3] => 1
> > )
> >
> >  [error]  Update failed: helfi_paragraphs_chart_update_9001
> >  [notice] Update started: helfi_paragraphs_contact_card_listing_update_9003
> >  [error]  SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'en-38' for key 'locales_target.PRIMARY': INSERT INTO "locales_target" ("lid", "language", "translation", "customized") VALUES (:db_insert_placeholder_0, :db_insert_placeholder_1, :db_insert_placeholder_2, :db_insert_placeholder_3); Array
> > (
> >     [:db_insert_placeholder_0] => 38
> >     [:db_insert_placeholder_1] => en
> >     [:db_insert_placeholder_2] => Ylempi sisältöalue
> >     [:db_insert_placeholder_3] => 1
> > )
> >
> >  [error]  Update failed: helfi_paragraphs_contact_card_listing_update_9003
> >  [notice] Update started: helfi_paragraphs_content_liftup_update_9001
> >  [error]  SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'en-38' for key 'locales_target.PRIMARY': INSERT INTO "locales_target" ("lid", "language", "translation", "customized") VALUES (:db_insert_placeholder_0, :db_insert_placeholder_1, :db_insert_placeholder_2, :db_insert_placeholder_3); Array
> > (
> >     [:db_insert_placeholder_0] => 38
> >     [:db_insert_placeholder_1] => en
> >     [:db_insert_placeholder_2] => Ylempi sisältöalue
> >     [:db_insert_placeholder_3] => 1
> > )
> >`

Mulla antaa erikoista duplikaattivirhettä joka johtaa feilanneihiin tuonteihin.

Ja tällasen printin antaa ku ajan deployn cr jälkeen:
` [notice] Database updates start.
>  [error]   (Currently using Incompatible module The following module is installed, but it is incompatible with Drupal 10.2.4:
>  * helfi_helsinki_profiili_audit_logging`

Näyttäs olevan vielä tuo moduli yhteensopimaton D10 kanssa.

DB päivitykset meni kuitenkin läpi, mutta konffituonti kaatuu:

![image](https://github.com/City-of-Helsinki/hel-fi-drupal-grants/assets/892920/27d7915c-a83b-4bb1-9be5-9464bddf716b)

2024-03-20 06:52 UTC, jiisuominen commented
+ merge konfliktit

2024-03-25 12:39 UTC, oskarimysteerio commented
Random huomioita:

Kirjaudu sivulla random viiva (Liittyiskö mahdollisesti johonkin HP moduulin tulevaan päivitykseen teeman puolella?)
![image](https://github.com/City-of-Helsinki/hel-fi-drupal-grants/assets/43133397/c7c87517-56eb-4fbf-ad47-01e11ddace4b)

Lomakkeen luonnin yhteydessä:

![image](https://github.com/City-of-Helsinki/hel-fi-drupal-grants/assets/43133397/5b8e622c-7814-4591-a30b-0deed1b4ebde)

"Partially-completed form was found.." - Jonkun takii tää tulee enkuks aina, varmaan pitäis lisätä message filter moduulin jatkoks, samalla näyttäis tulevan toinen ilmotus kun vaihtelee sivuja:

![image](https://github.com/City-of-Helsinki/hel-fi-drupal-grants/assets/43133397/7f12500e-579d-4272-8472-d5a08fe0e20f)

Nää näyttäis olevan disabled_message moduulissa jo konfattuna, niin onkohan toi mennyt nyt rikki yms?

2024-03-25 12:49 UTC, oskarimysteerio commented
Tää requestStack juttu tais olla joku tiedossa oleva muutos mikä pitää tehdä? Nyt hakemuksen poisto kaatuu tämmöseen: 
![image](https://github.com/City-of-Helsinki/hel-fi-drupal-grants/assets/43133397/3a02f957-4fb2-4cc7-a3bf-e7218f1bd2ec)

2024-03-25 13:06 UTC, oskarimysteerio commented
Tää ikoni on hieman pienempi (Ainakin FF) vs stage

![image](https://github.com/City-of-Helsinki/hel-fi-drupal-grants/assets/43133397/891ce28b-0776-4cb2-92fb-69a45a46c25d)

![image](https://github.com/City-of-Helsinki/hel-fi-drupal-grants/assets/43133397/42ddfcf6-f169-4aaf-9867-d7b83dc4dd00)

2024-03-25 13:12 UTC, oskarimysteerio commented
Tooltipeillä joku pahamieli, eikä oikein tunnu avautuvan, samoin konsoliin tulee jotakin erroria: 

![image](https://github.com/City-of-Helsinki/hel-fi-drupal-grants/assets/43133397/e55177de-479b-48e7-9ed5-2381a06fc759)

2024-03-26 07:23 UTC, Puavo commented
Mä korjaan tuon request stackin

2024-04-03 11:23 UTC, jiisuominen commented
`Deprecated function: Creation of dynamic property Drupal\content_lock\ContentLock\ContentLock::$time is deprecated in Drupal\content_lock\ContentLock\ContentLock->__construct() (line 139 of modules/contrib/content_lock/src/ContentLock/ContentLock.php).
Deprecated function: Creation of dynamic property Drupal\publication_date\PublishedAtOrNowComputed::$value is deprecated in Drupal\Core\TypedData\TypedData->setValue() (line 102 of core/lib/Drupal/Core/TypedData/TypedData.php).`

2024-04-04 04:49 UTC, jiisuominen approved these changes
Näyttäs toimivan. Syteen tai saveen.

2024-04-04 04:54 UTC, merged