feat: AU-2008: profile/mandate selection redirects.
City-of-Helsinki/hel-fi-drupal-grants pull request #1348
Opened 2024-04-29 07:41 UTC by oskarimysteerio

# [AU-2008](https://helsinkisolutionoffice.atlassian.net/browse/AU-2008)

## What was done

* This pull request adds redirections to form/service pages when user try to access these without a correct role mandate (For example by using a direct link or having wrong role for the application.)

## How to install

* Make sure your instance is up and running on correct branch.
  * `git checkout feature/AU-2008-profile-selection-redirects`
  * `make fresh`
* Run `make drush-cr`

## How to test

* [ ] Get some direct url to an application for the role you want to test. (Should look something like this: https://hel-fi-drupal-grant-applications.docker.so/fi/hakemus/LOCALON-057-0000039/katso
* [ ] Log out from the service if you are logged in. Log in and DO NOT select any roles.
* [ ] Try to use the URL you saved. (This should redirect you to the role selection).
* [ ] Select the correct role and check that the service will redirect you to the application page.
* [ ] Repeat for all roles.

* [ ] Service pages: Find a service page which you don't have a correct role for.
* [ ] Click the "Vaihda asiointiroolia"
* [ ] Select a correct role and check that you are redirected to the service page.

## Designers review

* [ ] This PR does not need designers review
* [ ] This PR has been visually reviewed by a designer (Name of the designer)

## Automatic- / Regression tests

* [ ] This PR makes no changes that effects any tests. (This will be caught in automatic testing later on, but please, please run regression tests always on PR before asking for a review)
* [ ] This PR passes regression tests. (`make test-pw`)

## Other PRs

* Link to other PR

2024-05-03 09:50 UTC, Puavo commented
Ohjeiden mukaan toimiessa uudelleenohjaukset toimivat kuten pitää. Drupalin päässä on kuitenkin useampi liikkuva osa joten tämän toiminnallisuuden saa solmuun esim:

Kirjaudu sisään ja valitse mandaatti yksityishenkilönä.

Avaa lomake esim: https://hel-fi-drupal-grant-applications.docker.so/fi/uusi-hakemus/liikunta_toiminta_ja_tilankaytto

Drupal uudelleenohjaa ensin lomakkeelle: https://hel-fi-drupal-grant-applications.docker.so/fi/hakemus/liikunta_toiminta_ja_tilankaytto/2790/muokkaa

Tämän jälkeen Drupal toteaa ettei oikeudet riitä ja ohjaa asiointiroolin valintaan.

Kun tekee onnistuneen valtuutuksen niin Drupal ohjaa lomakkeelle. Lomake on kuitenkin yksityishenkilölle luotu joten oikeudet eivät riitä siihen. Lomake näkyy yksityishenkilön oma asiointi listassa ja sitä klikkaamalla päätyy asiointiroolin valintaan.

2024-05-03 09:54 UTC, Puavo commented
Toinen käytännön läheinen asia:

Drupalissa on palvelusivuja joilla ei ole linkitettyä webformia esim.: https://hel-fi-drupal-grant-applications.docker.so/fi/tietoa-avustuksista/kulttuurin-avustukset/taide-ja-kulttuuriavustukset-monivuotiset-toiminta Nämä on kuitenkin manuaalisesti osoitettu koskemaan rekisteröityjä yhdistyksiä.

Näillä sivuilla tulee linkki asiointiroolin valintaan ja valinnan jälkeen käyttäjä ohjataan takaisin palvelusivulle mutta tämän jälkeen käyttäjällä ei ole mahdollisuutta edetä hakemuksen tekemisessä odotettavalla tavalla.

Sama tilanne on myös mikäli hakuaika ei ole käynnissä.

Nämä eivät ole suoraan tämän tiketin asioita. Tehdään näistä tarvittaessa omat tikettinsä.

2024-05-03 10:44 UTC, Puavo requested changes

2024-05-03 10:44 UTC, Puavo commented on public/modules/custom/grants_handler/src/EventSubscriber/CompanySelectExceptionSubscriber.php
> +      $this->redirectService->setCurrentPageAsRedirectUri();
Tämä säilötään virheen sattuessa melko pysyvästi. Jos virheen jälkeen tekee muita asioita ja sen jälkeen hakee valtuutuksen niin silloinkin tehdään uudelleen ohjaus. Siinä tapauksessa toiminnallisuus ei vaikuta loogiselta.

2024-05-03 10:46 UTC, Puavo commented
Tuo TrustedRedirectResponse pitäisi minusta korjata pois. Muilta osin pitäisi ensin speksata tarkemmin ja sen pohjalta säätää toiminnallisuutta. Uudelleenohjaukset toimivat kuten odottaa sopii suunnitelluissa käyttötilanteissa mutta joissakin muissa tilanteissa käytös voi yllättää.

2024-05-06 07:35 UTC, jiisuominen commented
> Ohjeiden mukaan toimiessa uudelleenohjaukset toimivat kuten pitää. Drupalin päässä on kuitenkin useampi liikkuva osa joten tämän toiminnallisuuden saa solmuun esim:
> 
> Kirjaudu sisään ja valitse mandaatti yksityishenkilönä.
> 
> Avaa lomake esim: https://hel-fi-drupal-grant-applications.docker.so/fi/uusi-hakemus/liikunta_toiminta_ja_tilankaytto
> 
> Drupal uudelleenohjaa ensin lomakkeelle: https://hel-fi-drupal-grant-applications.docker.so/fi/hakemus/liikunta_toiminta_ja_tilankaytto/2790/muokkaa
> 
> Tämän jälkeen Drupal toteaa ettei oikeudet riitä ja ohjaa asiointiroolin valintaan.
> 
> Kun tekee onnistuneen valtuutuksen niin Drupal ohjaa lomakkeelle. Lomake on kuitenkin yksityishenkilölle luotu joten oikeudet eivät riitä siihen. Lomake näkyy yksityishenkilön oma asiointi listassa ja sitä klikkaamalla päätyy asiointiroolin valintaan.

Tehdään tää nyt tällä tiketillä korjaukseen, että saatais mahd ripeästi käyttöön.

2024-05-10 11:10 UTC, Puavo reviewed
Testailin ja muutokset vaikuttavat toimivan.

2024-05-13 09:07 UTC, Puavo submitted a review, later dismissed
Ajoin vielä phpcbf:n joka poisti ylimääräisen use statementin

2024-05-13 09:57 UTC, jiisuominen commented
> Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: The service "grants_handler.event_subscriber" has a dependency on a non-existent service "grants_mandate_redirect.service".

jostain tollasesta herjaa huolella.

2024-05-15 05:12 UTC, jiisuominen commented
> Ohjeiden mukaan toimiessa uudelleenohjaukset toimivat kuten pitää. Drupalin päässä on kuitenkin useampi liikkuva osa joten tämän toiminnallisuuden saa solmuun esim:
> 
> Kirjaudu sisään ja valitse mandaatti yksityishenkilönä.
> 
> Avaa lomake esim: https://hel-fi-drupal-grant-applications.docker.so/fi/uusi-hakemus/liikunta_toiminta_ja_tilankaytto
> 
> Drupal uudelleenohjaa ensin lomakkeelle: https://hel-fi-drupal-grant-applications.docker.so/fi/hakemus/liikunta_toiminta_ja_tilankaytto/2790/muokkaa
> 
> Tämän jälkeen Drupal toteaa ettei oikeudet riitä ja ohjaa asiointiroolin valintaan.
> 
> Kun tekee onnistuneen valtuutuksen niin Drupal ohjaa lomakkeelle. Lomake on kuitenkin yksityishenkilölle luotu joten oikeudet eivät riitä siihen. Lomake näkyy yksityishenkilön oma asiointi listassa ja sitä klikkaamalla päätyy asiointiroolin valintaan.

PItäskö näitä Paavon maalailemia erikoistilanteita ottaa huomioon? Tässä PR tai tehdä uudet tiketit?

@Puavo ? @oskarimysteerio ?

2024-05-15 06:00 UTC, oskarimysteerio commented
> > Ohjeiden mukaan toimiessa uudelleenohjaukset toimivat kuten pitää. Drupalin päässä on kuitenkin useampi liikkuva osa joten tämän toiminnallisuuden saa solmuun esim:
> > Kirjaudu sisään ja valitse mandaatti yksityishenkilönä.
> > Avaa lomake esim: https://hel-fi-drupal-grant-applications.docker.so/fi/uusi-hakemus/liikunta_toiminta_ja_tilankaytto
> > Drupal uudelleenohjaa ensin lomakkeelle: https://hel-fi-drupal-grant-applications.docker.so/fi/hakemus/liikunta_toiminta_ja_tilankaytto/2790/muokkaa
> > Tämän jälkeen Drupal toteaa ettei oikeudet riitä ja ohjaa asiointiroolin valintaan.
> > Kun tekee onnistuneen valtuutuksen niin Drupal ohjaa lomakkeelle. Lomake on kuitenkin yksityishenkilölle luotu joten oikeudet eivät riitä siihen. Lomake näkyy yksityishenkilön oma asiointi listassa ja sitä klikkaamalla päätyy asiointiroolin valintaan.
> 
> PItäskö näitä Paavon maalailemia erikoistilanteita ottaa huomioon? Tässä PR tai tehdä uudet tiketit?
> 
> @Puavo ? @oskarimysteerio ?

Toisesta tehtiin tiketti mikä tais mennä Alexanderille ja toinen korjattu tässä

2024-05-20 12:30 UTC, jiisuominen approved these changes
Toimii

2024-05-20 12:32 UTC, merged