Minor frontend fixes for templates, styles and javascripts
City-of-Helsinki/hel-fi-drupal-grants pull request #1412
Opened 2024-06-03 09:05 UTC by khalima

## What was done

* Updated hdbt theme to ^6 and hdbt_admin theme to ^3.
* Removed favicon from global theme settings as favicons are not used in this way in helfi drupal instances.
* Converted jQuery.once to Drupal.once as jQuery.once is deprecated (in profile_dialog.js).
* Removed override javascript for accordions as the accordions have been heavily refactored in hdbt ^6.0.
* Fixed indentations from node--service templates.
* Updated webpack tools based on https://github.com/City-of-Helsinki/drupal-helfi-platform/blob/main/public/themes/custom/hdbt_subtheme/webpack.config.js.
* Updated node modules.
* Added some margin-top to main-content when user is browsing 'asiointirooli-valtuutus' page.

## How to install

* Make sure your instance is up and running on correct branch.
  * `git checkout UHF-9942`
  * `make fresh`
* Run `make drush-cr`

## How to test

* [ ] Open console from browser and check that there is no errors like: 
   ```
   GET https://avustukset.hel.fi/sites/default/files/favicon-32x32_0.ico 404 (Not Found)
   ```
   ```
   When editing own contact information: 
   drupal.js?v=10.2.6:64 Uncaught TypeError: $(...).once is not a function at Object.attach (profile_dialog.js?v=1.x:20:14)
   ```
* [ ] Check that the accordions do not give errors like: 
   ```
   TypeError: Cannot set properties of undefined (setting 'process') at s.saveItemState (accordion.min.js?v=1.3:1:3082)
   ```

* [ ] Check that code follows our standards

2024-06-03 11:12 UTC, strangeworlder approved these changes

2024-06-03 12:04 UTC, jiisuominen commented
Mites noi Sonarherjat? @khalima saiskohan ne helposti pois vai ignoretaanko?

2024-06-03 12:51 UTC, strangeworlder requested changes
Nevermind

2024-06-03 12:52 UTC, strangeworlder approved these changes

2024-06-04 04:20 UTC, merged

2024-06-04 05:11 UTC, khalima commented
> Mites noi Sonarherjat? @khalima saiskohan ne helposti pois vai ignoretaanko?

Mä korjasin siitä filusta kaikki muut paitsi ne nestaukset. Vois ehkä nostaa sitä nestaus limittiä ku drupalin behaviors tuo väkisinkin jo pari kerrosta jokaiseen toiminnallisuuteen - vaikkei toiminnallisuus tekis mitään. 😁