fix: AU-2443: make hero img not focusable
City-of-Helsinki/hel-fi-drupal-grants pull request #1421
Opened 2024-06-06 07:56 UTC by suvikankare

# [AU-2443](https://helsinkisolutionoffice.atlassian.net/browse/AU-2443)

## What was done

* Hero img got broken when focusing to it with screen reader, made the element not focusable (line 72)
* Kind of a purkka-ratkaisu, but this is hdbt-level problem that will probably be properly fixed at some point

## How to install

* Make sure your instance is up and running on correct branch.
  * `git checkout feature/AU-2443-hero-img`
  * `make fresh`
* Run `make drush-cr`

## How to test

* [ ] Go to front page, have NVDA on
* [ ] Put caret browsing on (was f7 in my keyboard)
* [ ] Scroll down with down-arrow on the keyboard, pass hero-element
* [ ] Scroll back up, pass hero-element
* [ ] Make sure that bg image in hero does not activate and image stays put

## Automatic- / Regression tests

* [x] This PR makes no changes that effects any tests. (This will be caught in automatic testing later on, but please, please run regression tests always on PR before asking for a review)
* [ ] This PR passes regression tests. (`make test-pw`)

2024-06-06 09:49 UTC, strangeworlder commented
@suvikankare - jos selaa reilusti herosta ohi ja palaa takaisin sivun alkuun, kuva hyppää ainakin minulla vielä vanhaan tyyliin.

2024-06-07 07:23 UTC, strangeworlder requested changes
Tosiaan, jos menee näppäimistöllä merkittävästi herokuvasta ohi ja palaa takaisin, errori toistuu

2024-06-07 08:29 UTC, suvikankare commented
@strangeworlder mä kävin footerissa asti mut kuva pysy paikallaan ylös palatessa 🙄

2024-06-10 09:59 UTC, strangeworlder approved these changes

2024-06-10 10:08 UTC, merged