Feature/uhf 10736
City-of-Helsinki/hel-fi-drupal-grants pull request #1496
Opened 2024-10-03 06:15 UTC by jiisuominen

# [UHF-0000](https://helsinkisolutionoffice.atlassian.net/browse/UHF-0000)

## What was done

* This thing was fixed

## How to install

* Make sure your instance is up and running on correct branch.
  * `git checkout UHF-0000_insert_correct_branch`
  * `make fresh`
* Run `make drush-cr`

## How to test

* [ ] Check that this feature works
* [ ] Check that code follows our standards

## Designers review

* [ ] This PR does not need designers review
* [ ] This PR has been visually reviewed by a designer (Name of the designer)

## Automatic- / Regression tests

* [ ] This PR makes no changes that effects any tests. (This will be caught in automatic testing later on, but please, please run regression tests always on PR before asking for a review)
* [ ] This PR passes regression tests. (`make test-pw`)

## Other PRs

* Link to other PR

2024-10-08 08:12 UTC, tuutti requested changes

2024-10-08 08:12 UTC, tuutti commented on public/modules/custom/grants_attachments/src/AttachmentFixerService.php
> +    private readonly Messenger $messenger,
Messenger service is not used and can be removed

2024-10-08 08:12 UTC, tuutti commented on public/modules/custom/grants_attachments/src/AttachmentFixerService.php
> +    $handlerOk = $this->filterEventsByTypeAndFilename($events, 'HANDLER_ATT_OK', $attachment['filename']);
`filterEventsByTypeAndFilename` expects `$events` and `$attachment` to be an array, but this method allows `mixed` type for both. The type should be checked/enforced before calling the method.

2024-10-08 08:12 UTC, tuutti commented on public/modules/custom/grants_attachments/src/AttachmentFixerService.php
> +    $avus2Ok = $this->filterEventsByTypeAndFilename($events, 'AVUSTUS2_ATT_OK', $attachment['filename']);
Same as above.

2024-10-08 08:12 UTC, tuutti commented on public/modules/custom/grants_attachments/src/AttachmentFixerService.php
> +    $avus2Error = $this->filterEventsByTypeAndFilename($events, 'AVUSTUS2_ATT_ERROR', $attachment['filename']);
Same as above.

2024-10-08 08:12 UTC, tuutti commented on public/modules/custom/grants_attachments/src/AttachmentFixerService.php
> +      $filenameFound = $this->findValueById($info, 'fileName', $attachment['filename']);
`findValueById` expects `$info` and `$attachment` to be an array, but this method allows `mixed` type for both. The type should be enforced before calling the method.

2024-10-10 07:09 UTC, tuutti approved these changes

2024-10-11 05:21 UTC, juho-lehmonen approved these changes

2024-10-11 05:24 UTC, merged