AU-666: Delete bank confirmation files automatically
City-of-Helsinki/hel-fi-drupal-grants pull request #192
Opened 2023-03-01 13:24 UTC by Krisseck

# [AU-666](https://helsinkisolutionoffice.atlassian.net/browse/AU-666)

## What was done

Bank account confirmation files are automatically deleted from ATV.

## How to install

- nothing required

## How to test

* [ ] Add a bank account and confirmation file to profile
* [ ] Delete said bank account
* [ ] Check logs that ATV file deletion succeeded

2023-03-02 05:43 UTC, jiisuominen commented
Oh, apologies. This should also fix the bank account change on application. Updated the ticket as well.

Sorry.

2023-03-02 05:44 UTC, jiisuominen requested changes
Sorry about bad specs.

2023-03-13 05:51 UTC, jiisuominen submitted a review, later dismissed
Toimiiks tää jo? Ei committeja moniin päiviin?

2023-03-13 05:58 UTC, Krisseck commented
No ei varsinaisesti toimi, haluan testata sen kunnolla, mutta en saa vielä VPN:ää toimimaan 

On March 13, 2023 7:51:24 AM GMT+02:00, Janne Suominen ***@***.***> wrote:
>@jiisuominen requested changes on this pull request.
>
>Toimiiks tää jo? Ei committeja moniin päiviin?
>
>
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/City-of-Helsinki/hel-fi-drupal-grants/pull/192#pullrequestreview-1336281511
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

2023-03-20 06:55 UTC, Puavo commented
Mä aloitin perjantaina katselemaan tätä. SonarCloud valittelee että sisennyksiä on liikaa.

Omana kommenttina renderöinti komennon elseif:in ehdossa on aika raskasta luettavaa. Mä korjailen näitä.

2023-03-20 09:12 UTC, jiisuominen commented on public/modules/custom/grants_attachments/src/AttachmentHandler.php
> +                  str_contains($attachment['value'], t('Confirmation for account @accountNumber', ['@accountNumber' => ''])->render())
Joo, eli ongelma on se, että tässä testataan tota stringin sisältöä, joka on hieman arveluttava tapa.

Parempi tapa selvittää onko kyseessä liitteen validointitiedosto on tutkia fileType koodia. Pankkitilin vahvistusliitteet ovat fileType = 45

2023-03-21 07:11 UTC, Puavo commented
Koodit näyttävät nyt monta pykälää selkeämmältä.

2023-03-21 07:12 UTC, Puavo approved these changes
Hyvältä vaikuttaa.

2023-03-21 09:20 UTC, merged