Feature/au 488 new printing functionality
City-of-Helsinki/hel-fi-drupal-grants pull request #237
Opened 2023-03-16 12:38 UTC by Puavo

# [AU-4880](https://helsinkisolutionoffice.atlassian.net/browse/AU-488)

There is a new controller for print view for forms.
## What was done

* This thing was fixed

## How to install

* Make sure your instance is up and running on correct branch.
  * `git checkout feature/AU-488-new-printing-functionality`
  * `make fresh`
* Run `make drush-cr`

## How to test

* [ ] Create a new application and save it
* [ ] Go to /en/hakemus/{application_id}/tulosta_atv to see the new print view

There is a new template in `public/modules/custom/grants_handler/templates/grants-handler-print-atv-document.html.twig` That needs FE magic. pages variable has most of the application data in easy to access format. The atv_document variable contain full data from atv.

This is draft because there is still work to do but this is open for commenting.

2023-03-17 11:27 UTC, strangeworlder commented
@Puavo - Getting an empty page by following instructions. It prints the twig correctly, but inside the twig, going through the pages array, there is nothing there. Looks like I have values in atv_document variable in the twig, but pages variable is empty.

2023-03-20 10:31 UTC, strangeworlder commented
Näköjään nyt toimii ihan ok, eli ehkä joku make freshin ongelma edellisellä kerralla, kuka tietää

2023-04-11 07:18 UTC, jiisuominen requested changes
![image](https://user-images.githubusercontent.com/892920/231085186-976b6a04-70f9-40ab-b172-c69dbf715605.png)

Hakulomakkeella toiminnan kuvaus on tekstikenttänä?

2023-04-11 07:33 UTC, jiisuominen requested changes
![image](https://user-images.githubusercontent.com/892920/231088275-60dad116-4da7-4d66-8b14-dcdf5496fc52.png)

Myös osoite-, tilinumero- ja yhteyshenkilötiedot näyttäs puuttuvan hakemusdatasta.

2023-04-11 11:13 UTC, jiisuominen commented
> > ![image](https://user-images.githubusercontent.com/892920/231085186-976b6a04-70f9-40ab-b172-c69dbf715605.png)
> > Hakulomakkeella toiminnan kuvaus on tekstikenttänä?
> 
> Ah, tää on kun noi ei kulje nyt konffeissa. Pitää vaihtaa community_purpose business_purposeksi kliksuttelemalla. Mites me tämöiset hoidetaan tulevaisuudessa?

Käsin pitää tuoda lomakekonffit tuotantoon, ja sieltä sit valuvat muualle. Toki voi tuoda käsin omaanki ympäristöön.

Ei taida muuta tapaa olla. Ehkä käyttöä helpottamaan vois tehä jonkun Drushkomennon tms, mut en tiiä kuinka paljon se oikeesti jeesaa.

2023-04-11 11:21 UTC, strangeworlder commented
> > > ![image](https://user-images.githubusercontent.com/892920/231085186-976b6a04-70f9-40ab-b172-c69dbf715605.png)
> > > Hakulomakkeella toiminnan kuvaus on tekstikenttänä?
> > 
> > 
> > Ah, tää on kun noi ei kulje nyt konffeissa. Pitää vaihtaa community_purpose business_purposeksi kliksuttelemalla. Mites me tämöiset hoidetaan tulevaisuudessa?
> 
> Käsin pitää tuoda lomakekonffit tuotantoon, ja sieltä sit valuvat muualle. Toki voi tuoda käsin omaanki ympäristöön.
> 
> Ei taida muuta tapaa olla. Ehkä käyttöä helpottamaan vois tehä jonkun Drushkomennon tms, mut en tiiä kuinka paljon se oikeesti jeesaa.

Ehkä enemmän siihen, jos on tällainen keissi, jossa meillä on koodissa muutos, joka vaatii lomakekonffin muutosta, mutta lomakekonffin muutos ennen koodin muutosta rikkoo koodin ja päinvastoin, että mikä tässä olis fiksuin tapa näitä koordinoida.

2023-04-11 11:24 UTC, jiisuominen commented
> Ehkä enemmän siihen, jos on tällainen keissi, jossa meillä on koodissa muutos, joka vaatii lomakekonffin muutosta, mutta lomakekonffin muutos ennen koodin muutosta rikkoo koodin ja päinvastoin, että mikä tässä olis fiksuin tapa näitä koordinoida.

Jaa-a, ei huono kyssäri.

Olen avoin ideoille.

2023-04-11 11:25 UTC, jiisuominen commented
Mut siis oisko nää muutokset ollu sillee, että käsin tuomalla lomakkeen korjaantus?

2023-04-14 05:33 UTC, jiisuominen requested changes

2023-04-14 05:33 UTC, jiisuominen commented on public/modules/custom/grants_metadata/src/AtvSchema.php
> +          $pageId = 'lisatiedot_ja_liitteet';
Tästä kovakoodauksesta voi tulla ongelmia. Pitänee refaktoroida sillee, ettei tartte tota pageidtä kovakoodata.

2023-04-14 05:33 UTC, jiisuominen commented on public/modules/custom/grants_metadata/src/AtvSchema.php
> +                      'label' => json_encode($propertyLabel),
Näihin vois testata käyttää tota labelia "oikein" ja luoda vaik uus metadata -kenttä.

Mä luulen Avus2 selviävän siitä paremmin ku siitä, et käytetään tota labelia väärin

2023-04-14 05:33 UTC, jiisuominen commented on public/modules/custom/grants_metadata/src/TypedData/Definition/ApplicationDefinitionTrait.php
>      $info['community_country'] = DataDefinition::create('string')
Näyttää siltä, ettei hakemukset mee integraatiosta ees ATV, tän muutoksen tein, en tiiä johtuuko siitä. pitää testailla

2023-04-14 05:36 UTC, jiisuominen requested changes

2023-04-14 05:36 UTC, jiisuominen commented on public/modules/custom/grants_metadata/src/AtvSchema.php
> +        if ($propertyName == 'community_street' || $propertyName == 'community_city' || $propertyName == 'community_post_code' || $propertyName == 'community_country') {
kaikki nää kovakoodaukset pitäs saada pois, eeehkä ton osotteen kanssa pystytään/joudutaan elämään koska se tulee kuitenki kustomikomponentista.

2023-05-08 04:27 UTC, jiisuominen approved these changes

2023-05-08 04:29 UTC, merged