Feature/au 804 integration messages
City-of-Helsinki/hel-fi-drupal-grants pull request #255
Opened 2023-03-22 06:51 UTC by jiisuominen

# [AU-804](https://helsinkisolutionoffice.atlassian.net/browse/AU-804)

There was some issues with message attachments: It did not support env changes done with integration so the attachments did not go through. Also attachments were uploaded in form submit so no errors could be shown inline. This fixes both of those.

## What was done

* Refactor message attachments to be saved to ATV in validate call. This allows us to show errors to user before submitting the form itself.
* Add environment part to attachment integrationID so Fuse can deliver correct attachment to Avus2
* Some code style things now that we have SonarLint working.

## How to install

* Make sure your instance is up and running on correct branch.
  * `git checkout UHF-0000_insert_correct_branch`
  * `make fresh`
* Run `make drush-cr`

## How to test

* [ ] Open application that is in Avus2 (status > DRAFT)
* [ ] Add message with attachment
* [ ] Check application content from ATV and see that message attachment integration id has your environment prefix
![image](https://user-images.githubusercontent.com/892920/226824048-19c5301e-d8fc-4a3e-be6f-7b6f2b44fdb7.png)
* [ ] Also check that the message attachment itself is in applications attachments object
![image](https://user-images.githubusercontent.com/892920/226824195-af9ac153-2709-48a2-ac55-5ed89f84228b.png)
* [ ] Ask Tero to reply your message (provide application number to him)
* [ ] Make sure the message & attachment is indeed in Avus2 from Tero
* [ ] Make sure the message appears in ATV & in application page

## Designers review

* [ ] This PR does not need designers review
* [x] This PR has been visually reviewed by a designer (Name of the designer)

2023-03-22 09:23 UTC, Puavo requested changes
Koodi käyty ajatuksella läpi.

2023-03-22 09:23 UTC, Puavo commented on public/modules/custom/grants_handler/src/Form/MessageForm.php
> +        catch (\Throwable $e) {
Mikäli upload feilaa niin ilmeisesi halutaan jatkaa yrittämistä muilla tiedostoilla jolloin jokaiselle elementille saadaan virheviesti?

2023-03-22 09:23 UTC, Puavo commented on public/modules/custom/grants_handler/src/Form/MessageForm.php
> +    if (str_contains($triggeringElement["#name"], 'messageAttachment_upload_button')) {
Tyyliasioista keskusteltiinkin itse suosisin alla olevaa muotoa mutta en aloita asiasta tappelua jos et tee muutoksia.

```suggestion
    if (!str_contains($triggeringElement["#name"], 'messageAttachment_upload_button')) {
      return;
    }
```

2023-03-22 09:23 UTC, Puavo commented on public/modules/custom/grants_handler/src/Form/MessageForm.php
> +  public static function validateUpload(array &$element, FormStateInterface $formState, array &$form) {
Onko jotain syytä olla laittamatta tietoa funktion paluuarvosta?

```suggestion
  public static function validateUpload(array &$element, FormStateInterface $formState, array &$form): void {
```

2023-03-22 09:23 UTC, Puavo commented on public/modules/custom/grants_handler/src/Form/MessageForm.php
> +   * @throws \Drupal\helfi_atv\AtvDocumentNotFoundException
Onko muualla koodissa jotain joka käsittelee nämä vai läväytetäänkö käyttäjälle virhe suoraan naamalle?

2023-03-22 09:23 UTC, Puavo commented on public/modules/custom/grants_handler/src/Form/MessageForm.php
> +   * Validate & upload file attachment.
Funktiota käytetään uploadaamiseen vaikka formissa se on kytketty validate-toiminnallisuuteen. Ehkä asiaa voisi parilla sanalla avata kommentissa miksi näin on.

2023-03-22 14:00 UTC, jiisuominen commented on public/modules/custom/grants_handler/src/Form/MessageForm.php
> +        catch (\Throwable $e) {
Tietysti. Miten se vois toimia muuten? Nii joo unohtaa muut tiedostot jos tulee virhe? Ei me niin tehdä, se johtaa kaikenlaisiin ongelmiin.

2023-03-22 14:00 UTC, jiisuominen commented on public/modules/custom/grants_handler/src/Form/MessageForm.php
> +        catch (\Throwable $e) {
Ellei täs nyt oo jotain mitä mä en hiffaa.

2023-03-22 14:01 UTC, jiisuominen commented on public/modules/custom/grants_handler/src/Form/MessageForm.php
> +    if (str_contains($triggeringElement["#name"], 'messageAttachment_upload_button')) {
Ei mulla oo väliä. Toi on edelleen musta huono tapa tehdä toi, mut jos sä ja Sonar ootte toista mieltä ni mitäpä mä siihen inttämään.

2023-03-22 14:11 UTC, jiisuominen commented on public/modules/custom/grants_handler/src/Form/MessageForm.php
> +  public static function validateUpload(array &$element, FormStateInterface $formState, array &$form) {
koska phpstorm ei sitä tarjonnu

2023-03-23 06:35 UTC, Puavo submitted a review, later dismissed
Näyttää hyvältä!

2023-03-23 10:55 UTC, Puavo commented
Toiminnallisuus testattu.

Löysin liitteisiin liittyvän ongelman mutta se ei liity erityisesti tähän PR:ään joten tein siitä oman tiksun.

2023-03-23 12:54 UTC, merged