fix: AU-769: Disable certain fields in service edit form if webform field is selected
City-of-Helsinki/hel-fi-drupal-grants pull request #262
Opened 2023-03-24 08:20 UTC by Puavo

# [AU-769](https://helsinkisolutionoffice.atlassian.net/browse/AU-769)

* Ehkäistään sisällönsyöttäjien ihmettelyä 

## What was done

* Järjestele kenttiä service nodetyypin lomakkeella
* Disabloi kenttiä mikäli webform kenttään on valittu jotain

## How to install

* Make sure your instance is up and running on correct branch.
  * `git checkout feature/AU-769-node-edit-form`
  * `make fresh`
* Run `make drush-cr`

## How to test

* [ ] Mene luomaan tai muokkaamaan service-tyyppistä sisältöä
* [ ] Kun webform-kentässä, joka on nyt heti otsikon jälkeen, on valittuna jotain alla olevat kentät menevät disabled tilaan. Kun valintaa ei ole niitä voi muokata.

## Designers review

* [ ] This PR does not need designers review
* [ ] This PR has been visually reviewed by a designer (Name of the designer)

2023-03-27 11:28 UTC, jiisuominen commented
![image](https://user-images.githubusercontent.com/892920/227923811-db0f87d1-645a-432c-b41d-0f101640be21.png)

Halutaankohan me sallia edes noita webformin statuksia tällä lomakkeella? Jotenki tuntuu, että ei.

2023-03-27 11:28 UTC, jiisuominen requested changes
Ton lomakkeen asetusosan voi varmaan laittaa kokonaan piiloon.

2023-03-28 09:52 UTC, Puavo commented
Settings osio piilotettu lomakkeelta.

2023-03-29 08:02 UTC, jiisuominen approved these changes

2023-03-29 08:03 UTC, merged