Feature/au 887 budget income static component
City-of-Helsinki/hel-fi-drupal-grants pull request #331
Opened 2023-04-18 12:44 UTC by oskarimysteerio

### Draft

# [UHF-0000](https://helsinkisolutionoffice.atlassian.net/browse/UHF-0000)

## What was done

* This thing was fixed

## How to install

* Make sure your instance is up and running on correct branch.
  * `git checkout UHF-0000_insert_correct_branch`
  * `make fresh`
* Run `make drush-cr`

## How to test

* [ ] Check that this feature works
* [ ] Check that code follows our standards

## Designers review

* [ ] This PR does not need designers review
* [ ] This PR has been visually reviewed by a designer (Name of the designer)

## Other PRs

* Link to other PR

2023-04-24 05:41 UTC, jiisuominen commented
![image](https://user-images.githubusercontent.com/892920/233909094-8e280d30-7da9-4b21-83be-9ffb140eb7b7.png)

Remove nappi

2023-04-24 05:44 UTC, jiisuominen commented
![image](https://user-images.githubusercontent.com/892920/233909365-fdae0a55-5055-47d2-9bc8-181c38811d88.png)

What's that ID?

2023-04-24 07:04 UTC, Puavo requested changes

2023-04-24 07:04 UTC, Puavo commented on public/modules/custom/grants_handler/src/Plugin/WebformHandler/GrantsHandler.php
> +    foreach (array_keys($budgetFields) as $element) {
Mä muuttaisin tässä kohtaa $element => $elementKey niin looppi on monta kertaa helpompi lukea.

2023-04-24 07:07 UTC, Puavo commented
Vähän korkeamman tason kommentti mutta mulle jäi lomaketta täyttäessä epäselväksi onko lomakkeisiin tarkoitus laittaa numeroita vai jotain muuta. Fronttityypeillä on varmasti ajatuksia tilanteen parantamisesta jos nähdään syytä parantaa asiaa.

2023-04-24 08:14 UTC, jiisuominen commented on public/modules/custom/grants_budget_components/src/Element/GrantsBudgetCostStatic.php
> +  // @codingStandardsIgnoreStart
Mä epäilen tota jäänteeks sieltä ajalta ku ei menny deployt läpi sonarcloudvirheistä.

2023-04-24 08:15 UTC, jiisuominen commented
> Vähän korkeamman tason kommentti mutta mulle jäi lomaketta täyttäessä epäselväksi onko lomakkeisiin tarkoitus laittaa numeroita vai jotain muuta. Fronttityypeillä on varmasti ajatuksia tilanteen parantamisesta jos nähdään syytä parantaa asiaa.

Tää siis tosiaankin suhteellisen tyypillinen ongelma kun ei voida käyttää selaimen omia "number" kenttiä. Ehkä sillä inputmaskilla tätäki vois taklata, @strangeworlder ?

2023-04-24 10:20 UTC, strangeworlder commented
> > Vähän korkeamman tason kommentti mutta mulle jäi lomaketta täyttäessä epäselväksi onko lomakkeisiin tarkoitus laittaa numeroita vai jotain muuta. Fronttityypeillä on varmasti ajatuksia tilanteen parantamisesta jos nähdään syytä parantaa asiaa.
> 
> Tää siis tosiaankin suhteellisen tyypillinen ongelma kun ei voida käyttää selaimen omia "number" kenttiä. Ehkä sillä inputmaskilla tätäki vois taklata, @strangeworlder ?

Input mask vois varmaan toimia tai voidaan tehdä oma "number" -elementti, joka ylikirjoittaa meidän number fieldin. Se on ehkä parempi, koska sit kukaan ei vahingossa pistä noita numbereita tulevaisuudessakaan, vaan meidän feikkinumberin, joka on input=text, jossa vaan regexpataan, mitä siihen voi laittaa. Teen tästä tiketin.

2023-04-25 05:26 UTC, jiisuominen commented on public/modules/custom/grants_metadata/src/TypedData/Definition/KuvaProjektiDefinition.php
> +      /* Not in use for this application (?).
Imo ei ongelmaa jättää, koska tulee käyttöön kuitenki jo seuraavassa lomakkeessa jossa päästään testaamaan. Toinen vaihtoehto on tietty kopsii talteen johonki muualle ja pastee takas ku tarvitaan.

En nää ongelmaa tässäkään tosin.

2023-04-27 06:45 UTC, jiisuominen approved these changes

2023-04-27 06:45 UTC, merged