feat: AU-880: Create styles for new roles/profiles
City-of-Helsinki/hel-fi-drupal-grants pull request #334
Opened 2023-04-20 13:33 UTC by suvikankare

# [AU-880](https://helsinkisolutionoffice.atlassian.net/browse/AU-880)

## What was done

* This thing was fixed

## How to install

* Make sure your instance is up and running on correct branch.
  * `git checkout feature/AU-880-hakuprofiilit`
  * `make fresh`
* Run `make drush-cr`

## How to test

* [ ] Check that this feature works
* [ ] Check that code follows our standards

## Designers review

* [ ] This PR does not need designers review
* [ ] This PR has been visually reviewed by a designer (Name of the designer)

## Other PRs

* Link to other PR

2023-04-25 05:28 UTC, jiisuominen commented
Mergesin profiililomakebranchin niin sun pitäs päästä tässäki eteenpäin..

2023-04-26 07:33 UTC, strangeworlder requested changes

2023-04-26 07:34 UTC, strangeworlder commented on public/modules/custom/grants_profile/translations/sv.po
"Country" on privage person does not get translated.

2023-04-27 04:42 UTC, strangeworlder approved these changes

2023-04-27 05:03 UTC, merged