fix: AU-993: Add sv translations
City-of-Helsinki/hel-fi-drupal-grants pull request #361
Opened 2023-05-02 10:52 UTC by suvikankare

# [AU-993](https://helsinkisolutionoffice.atlassian.net/browse/AU-993)

## What was done

* Added a bunch of sv translations

## How to install

* Make sure your instance is up and running on correct branch.
  * `git checkout feature/AU-993-translations`
  * `make fresh`
* Run `make drush-cr`

## How to test

* [ ] Check that the translations work

2023-05-03 04:05 UTC, jiisuominen requested changes

2023-05-03 04:05 UTC, jiisuominen commented on public/modules/custom/grants_handler/config/install/grants_handler.settings.yml
> +    RECEIVED: Mottagits
Mikä tää on?

Vaa yks noista käännetty?

2023-05-03 05:34 UTC, suvikankare commented on public/modules/custom/grants_handler/config/install/grants_handler.settings.yml
> +    RECEIVED: Mottagits
Kaikki on käännetty mitä tiketillä oli, siellä ei ollu näihin ku toi yks

2023-05-09 11:17 UTC, strangeworlder submitted a review, later dismissed

2023-05-15 07:41 UTC, jiisuominen approved these changes

2023-05-15 07:41 UTC, merged