AU-1022 Handle dummy boolean fields in webform
City-of-Helsinki/hel-fi-drupal-grants pull request #380
Opened 2023-05-08 13:38 UTC by Puavo

# [AU-1022](https://helsinkisolutionoffice.atlassian.net/browse/AU-1022)

Anna arvo webformin boolean kentille perustuen toiseen kenttään. Tämä on tarpeen koska formilla on kenttiä joita ei talleteta ATV:hen.

## What was done

Määritä webformextracter metodi ja tee siihen liittyen sopivat määrittelyt

* This thing was fixed

## How to install

* Make sure your instance is up and running on correct branch.
  * `git checkout feature/AU-1022-radiobuttons`
  * `make fresh`
* Run `make drush-cr`

## How to test

Kirjaudu sisään ja mene https://hel-fi-drupal-grant-applications.docker.so/fi/form/kuva-toiminta

Lomakkeen sivulla 2 paina kyllä Kyseessä on monivuotinen avustus radiobuttonille ja täytä kenttä  "Tulevat vuodet joiden ajalle monivuotista avustusta on haettu tai myönnetty".

Tallenna keskeneräisenä

Palaa lomakkeelle ja varmista että radiobutton on kyllä asennossa ja mainitussa kentässä on oikea arvo

Tyhjennä kenttä ja tallenna keskeneräisenä.

Palaa lomakkeelle ja radiobutton on ei asennossa.

Katselmoi koodia ajatuksella. Ovatko nimet hyviä, tätä logiikkaa on tarkoitus käyttää jatkossa useammassa paikassa.

* [ ] Check that this feature works
* [ ] Check that code follows our standards

## Designers review

* [ ] This PR does not need designers review
* [ ] This PR has been visually reviewed by a designer (Name of the designer)

## Other PRs

* Link to other PR

2023-05-09 05:21 UTC, jiisuominen reviewed
![image](https://user-images.githubusercontent.com/892920/237001057-c8bfb6da-9b6d-47cd-bbe4-87c0358a32a4.png)

^ Toimii.

![image](https://user-images.githubusercontent.com/892920/237001109-2b60875a-deae-46fb-b12e-ff6313ccde2a.png)

^ Ei toimi. Puuttuuko speksit vai kui?

2023-05-09 05:25 UTC, jiisuominen requested changes

2023-05-09 05:25 UTC, jiisuominen commented on public/modules/custom/grants_metadata/src/TypedData/Definition/KuvaToimintaDefinition.php
> +        ->setSetting('webformDataExtracter', [
Hmm. Pitäsköhän tää tehä samalla tavalla ku noissa valuecallbackeissa, että konffis tuolla definitionissa arguments ja sit passais ne eteenpäin sille funktiolle?

Meinaan, että ois yleiskäyttösempi ehkä jos jossain tarvitaan jatkossa jotain toista tapaa jumppailla näitä?

Like so:

`      $info['hanke_alkaa'] = DataDefinition::create('string')
        ->setLabel('Hanke alkaa.')
        ->setSetting('jsonPath', [
          'compensation',
          'activityInfo',
          'plannedActivityInfoArray',
          'projectStartDate',
        ])
        ->setSetting('typeOverride', [
          'dataType' => 'string',
          'jsonType' => 'datetime',
        ])
        ->setSetting('valueCallback', [
          'service' => 'grants_metadata.converter',
          'method' => 'convertDates',
          'arguments' => [
            'dateFormat' => 'c',
          ],
        ]);`

2023-05-09 05:48 UTC, Puavo commented
Tiketissä oli vain tuo yksi kenttä mainittuna. Lisään tuohon toiseenkin. Kun pohdin tuota arguments-asiaa.

2023-05-09 13:31 UTC, Puavo commented
Toinen kenttäpari lisätty ja muokattu ehdotuksen mukaisesti käyttämään arguments-parametria.

2023-05-10 04:20 UTC, jiisuominen commented
> Tiketissä oli vain tuo yksi kenttä mainittuna. Lisään tuohon toiseenkin. Kun pohdin tuota arguments-asiaa.

Niin siis tää tiketti tietysti koskee _kaikkia_ tällasia radiobuttoneita kaikissa hakemuksissa. Mut kunhan toi toteutus on kunnossa niin eipä ton lisääminen mikään amerikan temppu ole muihinkaan radioihin.

2023-05-10 05:05 UTC, jiisuominen commented
Voisit vielä kommentoida ton metodin, mulle ei ainakaan ihan heti tosta koodista selvinny toiminnan logiikka. Tarkalleen ottaen jäi vähän hämäräks slave/master jaottelu. Mut näyttäs siis toimivan, jos pitää palata jatkossa niin ois helpompi jatkaa jos ois kommentoitu ajatus takana.

Ja sit voisit pyytää uutta review ni sais ton "Changes requested" tilan -> "Review requested" tilaan.

2023-05-10 05:08 UTC, jiisuominen reviewed
Eiku voinhan mä täältä toista kautta approvee. 

Mut jos mä approveen nyt ja sä lisäät kommentit, niin sit sun pitää ehkä pyytää uusiks review kuitenki?

2023-05-10 06:35 UTC, Puavo commented
Teinkö mä nyt oikeanlaisen review requestin?

2023-05-10 07:01 UTC, Puavo commented
Mun push ei mennyt läpi aiemmin.

2023-05-10 11:01 UTC, merged