fix: AU-1088 Hidden summation field makes title display go away, no matter the setting.
City-of-Helsinki/hel-fi-drupal-grants pull request #448
Opened 2023-05-25 13:22 UTC by strangeworlder

# [AU-1088](https://helsinkisolutionoffice.atlassian.net/browse/AU-1088)

## What was done

* Make it so that hidden Sum component forces title display to be hidden

## How to install

* Make sure your instance is up and running on correct branch.
  * `git checkout feature/AU-1088-summation-field-hidden`
  * `make fresh`
* Run `make drush-cr`

## How to test

* [ ] Go to admin on projektiavustus
* [ ] See that the title display is set to before on avustusasiointi summa
* [ ] Go to the projektiavustus as end user
* [ ] see that you can't see the avustusasiointi summa.
* [ ] Check that code follows our standards

## Designers review

* [ ] This PR does not need designers review
* [ ] This PR has been visually reviewed by a designer (Name of the designer)

## Other PRs

* Link to other PR

2023-05-26 05:54 UTC, jiisuominen requested changes
![image](https://github.com/City-of-Helsinki/hel-fi-drupal-grants/assets/892920/1b8ab133-276d-4eea-ba18-884027af35f6)

2023-05-26 11:06 UTC, strangeworlder commented
Lisäsin previewistä hiddenin piilottavan twigin

2023-05-29 04:03 UTC, jiisuominen approved these changes

2023-05-29 04:15 UTC, jiisuominen requested changes
![image](https://github.com/City-of-Helsinki/hel-fi-drupal-grants/assets/892920/e0cd1c48-0067-4a42-84c2-1bf574a0bc62)

mites toi ei nyt mee kohilleen millään?

![image](https://github.com/City-of-Helsinki/hel-fi-drupal-grants/assets/892920/dcb52582-28e4-4929-9f05-c60815bdc89d)

miksei vaan laittas tyyleillä piiloon?

2023-05-29 10:55 UTC, oskarimysteerio commented
Näyttää mulle ok, kunhan clearaa kakut, että twig cachet tyhjenee -> Teksti katoaa tuosta Jannen kuvan kohdalta

2023-05-29 10:59 UTC, strangeworlder commented
@jiisuominen - en onnistu toistamaan summakentän näkyviin tulemista. Katsotko uudestaan ja otetaan vaikka puhelu, että näkee mistä on kyse jos sulla se näkyy vielä jossain

2023-05-29 11:44 UTC, jiisuominen commented
> Näyttää mulle ok, kunhan clearaa kakut, että twig cachet tyhjenee -> Teksti katoaa tuosta Jannen kuvan kohdalta

no tää on sit jotain mun sekoilua. vaikka kyllä makefresh pitäs kait tyhjää kakut ku tuo uuden kannan.. mut samapa tuo on.

jos toimii teillä ni en lähe tästä vääntämään :)

2023-05-29 11:44 UTC, jiisuominen commented
> @jiisuominen - en onnistu toistamaan summakentän näkyviin tulemista. Katsotko uudestaan ja otetaan vaikka puhelu, että näkee mistä on kyse jos sulla se näkyy vielä jossain

tsekkaa yllä, uskon teitä :)

2023-05-29 11:44 UTC, jiisuominen approved these changes

2023-05-29 11:45 UTC, merged