Feature/au 1032 autologout fixes
City-of-Helsinki/hel-fi-drupal-grants pull request #466
Opened 2023-05-30 11:33 UTC by Puavo

# [AU-1032](https://helsinkisolutionoffice.atlassian.net/browse/AU-1032)

Auto logoutiin liittyvät ongelmat:
- Käyttäjä kirjataan ulos vaikka modaali-ikkuna on edelleen auki
- Uudelleenohjaus ei toimi

## What was done

Luo uusi moduuli jossa päivitetään logiikka uloskirjaukseen
Säädä aikarajaa
Asenna patchi drupal orgista modaalia varten

## How to install

* Make sure your instance is up and running on correct branch.
  * `git checkout feature/AU-1032-autologout-fixes`
  * `make fresh`
* Run `make drush-cr`

## How to test

* [ ] Check that this feature works
* [ ] Check that code follows our standards

## Designers review

* [ ] This PR does not need designers review
* [ ] This PR has been visually reviewed by a designer (Name of the designer)

## Other PRs

* Link to other PR

2023-05-30 12:25 UTC, oskarimysteerio requested changes

2023-05-30 12:25 UTC, oskarimysteerio commented on public/modules/custom/autologout_extend/src/Routing/RouteSubscriber.php
> +      $route->setDefault('_controller', '\Drupal\grants_profile\Controller\GrantsProfileController::altLogout');
Tän tarvis luultavasti olla `autologout_extend` moduulin controll + method

2023-05-30 12:28 UTC, jiisuominen commented on public/modules/custom/autologout_extend/src/Routing/RouteSubscriber.php
> +      $route->setDefault('_controller', '\Drupal\grants_profile\Controller\GrantsProfileController::altLogout');
Jess. No mä en jatka testailua, jos @Puavo muutat ton ni testaan aamulla. Josko saatas vaikka huomenna käyttöön.

2023-05-31 05:15 UTC, jiisuominen commented
![image](https://github.com/City-of-Helsinki/hel-fi-drupal-grants/assets/892920/b27676d4-7123-4644-91d4-b52af557ba61)

Oskarin muutoksilla näyttäs jäävän tohon kii, kutsuu autologout endpointia mut ei tapahdu mitään.

2023-06-01 08:44 UTC, jiisuominen reviewed
En tiiä teenks jotain väärin, mutta mulla ei vaan tee tota autologoutia.

![image](https://github.com/City-of-Helsinki/hel-fi-drupal-grants/assets/892920/d2f3597c-52d8-4c7e-9424-61397cba3527)

käy kyselemässä endpointista aikoja etc, mut mitään ei tapahdu. ei kirjaa ulos eikä tuu modalia. ei midis.

2023-06-02 04:34 UTC, jiisuominen approved these changes
Toimii.

2023-06-02 04:34 UTC, merged