feat: AU-1052: Remove unregistered company
City-of-Helsinki/hel-fi-drupal-grants pull request #499
Opened 2023-06-08 06:00 UTC by Puavo

# [AU-1052](https://helsinkisolutionoffice.atlassian.net/browse/AU-1052)

Mahdollisuus poistaa rekisteröimätön yhdistys jolla ei ole hakemuksia avustus2:ssa.

## What was done

Näytä poista nappula muokatessa yhdistystä. (ei heti luonnin jälkeen)

## How to install

* Make sure your instance is up and running on correct branch.
  * `git checkout feature/AU-1052-remove-unregistered-company`
  * `make fresh`
* Run `make drush-cr`

## How to test

* [ ] Check that this feature works
* [ ] Check that code follows our standards

## Designers review

* [ ] This PR does not need designers review
* [ ] This PR has been visually reviewed by a designer (Name of the designer)

## Other PRs

* Link to other PR

2023-06-08 13:24 UTC, jiisuominen requested changes
![image](https://github.com/City-of-Helsinki/hel-fi-drupal-grants/assets/892920/bb4c909e-b440-4a36-96c6-b74e907476c6)

Oiskohan ton napin syytä olla eri värinen ja siinä vois olla vahvistuskysely.

Tai pitäsköhän toi nappi jopa siirtää pois tosta lomakkeelta tohon aikasemmalle sivulle?

![image](https://github.com/City-of-Helsinki/hel-fi-drupal-grants/assets/892920/90258a81-7038-4676-a42c-b4108ec313e9)

2023-06-08 13:25 UTC, jiisuominen commented
Ja sellanen vielä, että pitäsköhän ton kertoo syy miks poisto ei onnistunu? Tai siis jos ei tehdä poistoa jos on olemassaolevia hakemuksia? Ja ehkä kertoo jos poistetaan jotain?

2023-06-08 13:28 UTC, jiisuominen commented
![image](https://github.com/City-of-Helsinki/hel-fi-drupal-grants/assets/892920/68461523-b04b-4976-8d26-c0e01a3c70f1)

Ah, aivan. [AtvServicehän on contrib moduli](https://github.com/City-of-Helsinki/drupal-module-helfi-atv). Sun pitää lisätä toi sinne ja tehä sitä kautta pullari, uus versio jne

2023-06-08 13:51 UTC, Puavo commented
Tein byId helpottamaan testailua ja git ei sitä näytä niin unohtui. Korjaan asian.

2023-06-11 21:39 UTC, Puavo commented
Korjaukset ja muutokset pushattu

2023-06-13 06:06 UTC, jiisuominen commented
![image](https://github.com/City-of-Helsinki/hel-fi-drupal-grants/assets/892920/394f1ab5-6bd1-4ec9-b6a3-a97581283e98)

ummm mitä?

2023-06-13 06:08 UTC, jiisuominen commented
![image](https://github.com/City-of-Helsinki/hel-fi-drupal-grants/assets/892920/7732e61b-0c93-4983-905e-bc0472929e4f)

Saiskohan poistovahvistuksen modaliin?

Vähintään ulkoasu kuntoon.

2023-06-13 06:59 UTC, jiisuominen requested changes
Joo noi muutamat muutokset ja se modalioptio. @suvikankare saattaa tietää jotain niistä modaleista.

Ja pyydä uus review multa ku oot valmis. Haluun siis nähdä, että mitä kautta mulle noista ilmotellaan.

2023-06-13 13:45 UTC, Puavo commented
Modaali toteutettu. Käännöksiä paranneltu ja draftien käsittelyä parannettu.

2023-06-14 12:56 UTC, jiisuominen commented
Oonks mä nyt missannu jotain ku saan samanlaisen ilmotuksen ku aikasemminki?

![image](https://github.com/City-of-Helsinki/hel-fi-drupal-grants/assets/892920/52ff30f8-e4d1-4889-b953-460aa5bae057)

2023-06-14 13:02 UTC, jiisuominen commented
Muutama typo vielä tossa modalissa:
![image](https://github.com/City-of-Helsinki/hel-fi-drupal-grants/assets/892920/b5791849-570e-486b-b084-392940f31548)

2023-06-14 13:03 UTC, jiisuominen requested changes
Ylläolevien lisäks yksityishenkilön lomake sanoo näin:

`The website encountered an unexpected error. Please try again later.
Error: Call to undefined method Drupal\grants_profile\GrantsProfileService::setPrivatePersonRole() in Drupal\grants_mandate\Form\ApplicantMandateForm->submitForm() (line 257 of modules/custom/grants_mandate/src/Form/ApplicantMandateForm.php).`

2023-06-15 06:10 UTC, Puavo commented
Lisään vielä poistosyyn.

2023-06-16 09:30 UTC, jiisuominen approved these changes

2023-06-16 09:31 UTC, merged