AU-1169: Application acting years dynamic values
City-of-Helsinki/hel-fi-drupal-grants pull request #502
Opened 2023-06-08 10:18 UTC by Krisseck

# [AU-1169](https://helsinkisolutionoffice.atlassian.net/browse/AU-1169)

`Acting year` fied in forms is hardcoded to current year + 2 years.

## What was done

* Added new field to webform, so that `acting year` can be set per webform
* Changed the logic in application form to use this new field for initial year options

## How to install

* Make sure your instance is up and running on correct branch.
  * `git checkout UHF-0000_insert_correct_branch`
  * `make fresh`
* Run `make drush-cr`

## How to test

* [ ] Edit a webform
* [ ] Check that webform has field "Available acting years"
* [ ] Change field value
* [ ] Check that you get notification message that corresponding node was also updated
* [ ] Open new application with the form in question
* [ ] Go to step 2 of application form
* [ ] Check that `acting year` field has only the options available that you selected previously

## Designers review

* [x] This PR does not need designers review
* [ ] This PR has been visually reviewed by a designer (Name of the designer)

## Other PRs

* Link to other PR

2023-06-09 04:38 UTC, jiisuominen requested changes
Eli siis melkein. Jos nyt tulkitsin oikein, niin form_page nodetyypistä nuo muutokset webformin thirdpartysettingseihin.

Ja service pageen voitas jättää vuosiluvut. niillä ei välttis oo merkitystä mutta kun ovat siellä ni olkoot. Voitas vaan siellä webform/node savesta kaivaa vuosiluvut tallennuksen yhteydessä niinku muutkin tiedot. Siellä on siis presave hookit molemmille.

2023-06-12 09:52 UTC, jiisuominen commented on conf/cmi/core.entity_form_display.node.service.default.yml
> -  field_sidebar_content:
Tää mua vielä vähän huolestuttaa. Muuten näyttäs olevan kondiksessa.

Osaatko sanoo tästä enempää?

2023-06-12 09:57 UTC, jiisuominen requested changes
![image](https://github.com/City-of-Helsinki/hel-fi-drupal-grants/assets/892920/19332f04-a66f-4aa2-a575-12091e6a6257)

joo halutaan kyl pitää toi mukana. miten on tässä tipahtamassa?

2023-06-12 10:54 UTC, Krisseck commented on conf/cmi/core.entity_form_display.node.service.default.yml
> -  field_sidebar_content:
Veikkaan että joko mulla oli liian vanha versio developista, tai en ollut vetänyt make freshiä. Mutta ei tosiaan kuulu tähän mitenkään, korjattu.

2023-06-13 08:20 UTC, jiisuominen approved these changes

2023-06-13 08:21 UTC, merged