Feature/AU-1258: Application search with Search API
City-of-Helsinki/hel-fi-drupal-grants pull request #670
Opened 2023-08-24 10:58 UTC by Alexander-Tallqvist-Siili

# [AU-1258](https://helsinkisolutionoffice.atlassian.net/browse/AU-1258)

## What was done

This pull request implements a new application search that has been implemented with the help of the Search API module.

## How to install

Make sure your instance is up and running on the correct branch.
  * `git checkout feature/AU-1258-search-api`
  * `make fresh`
  * `make drush-cr`

## How to test
1. Start by going to `/admin/config/search/path?search=&sort=asc&order=System path` and delete the old aliases for `/etsi-avustusta`. Now implement two new aliases for `/application-search` like shown in the picture below:
<img width="1673" alt="image" src="https://github.com/City-of-Helsinki/hel-fi-drupal-grants/assets/117807015/35d3bb4a-26fa-4730-83b2-e64519176994">

2. Now go to `/admin/config/search/search-api/index/search_index` and index all the service pages to the search index.

3. Next, go to `/fi/etsi-avustusta` and test that the search works and produces good results. Also review the search in both English and Swedish and check that the translations work.

3. Finally review the settings for the search index, mainly at `/admin/config/search/search-api/index/search_index/fields` and `/admin/config/search/search-api/index/search_index/processors`. Do the field and processor settings look alright? Do we need to adjust any of the boost options for the indexed fields?

2023-08-28 04:48 UTC, jiisuominen commented
![image](https://github.com/City-of-Helsinki/hel-fi-drupal-grants/assets/892920/7d03ef5e-43a9-458b-aa15-cbd524920277)

mitähän toi tarkottaa tuolla CI testissä?

2023-08-28 04:49 UTC, jiisuominen requested changes
Muuten toimii todella hyvin, paitsi että otsikkokentästä ei näyttäis hakevan.

Oiskohan siihen mahollista saada wildcardhakua myös? Tai sanan alulla hakevaa, ehkä helpompi toteuttaa?

2023-08-28 09:25 UTC, oskarimysteerio commented
> ![image](https://user-images.githubusercontent.com/892920/263595776-7d03ef5e-43a9-458b-aa15-cbd524920277.png)
> 
> mitähän toi tarkottaa tuolla CI testissä?

@jiisuominen Kuten testin otsikossa lukee, niin buildasit tyylit dev-moodissa :D

2023-08-31 05:56 UTC, jiisuominen requested changes
Mulla tuli konflikteja tossa tyylitiedostosssa ja ajoin uusiks makella rakennuksen. 

Nyt näyttää melkein samalta ku vanha, mut jotain siinä on vielä:

![image](https://github.com/City-of-Helsinki/hel-fi-drupal-grants/assets/892920/508fc3f5-ac08-4f32-902d-b8696db73518)

Ja toinen huomio oli, että tossa viewissä oli polkuna application-search, muutin etsi-avustusta niin toimi normisti. Onks joku syy miksei ollu suoraan etsi-avustusta?

2023-08-31 06:05 UTC, Alexander-Tallqvist-Siili commented
@jiisuominen
- Tyyleistä en osaa sanoa miksi eivät toimi. Voin kurkata vielä.
- View on alunperin rakennettu englanniksi. Ajattelin, että olis loogisempaa, jos se viewn polku noudattaa sen viewn alkuperäistä kieltä. Mut kait sen voi tehä miten tahtoo.

2023-08-31 08:12 UTC, jiisuominen commented
> @jiisuominen
> 
> * Tyyleistä en osaa sanoa miksi eivät toimi. Voin kurkata vielä.

Joo siis mä en tajua niistä hirveästi, näyttää vaan erilaiselta. 

> * View on alunperin rakennettu englanniksi. Ajattelin, että olis loogisempaa, jos se viewn polku noudattaa sen viewn alkuperäistä kieltä. Mut kait sen voi tehä miten tahtoo.

Joo eihän tossa oo siis mitään ongelmaa, pitää vaan muistaa käydä kliksuttelemassa käsin nuo muutokset. Kelaan jos jättäis niin ku on ollu ni ois yks vähemmän säädettäväks. Tarviskohan niitä aliaksia ees poistaa?

2023-08-31 08:25 UTC, jiisuominen commented
@Alexander-Tallqvist-Siili tällasen huomasin vielä:
![image](https://github.com/City-of-Helsinki/hel-fi-drupal-grants/assets/892920/db652724-8863-46d1-b549-f758f995970f)

Oisko otsikon jemmaus viewistä ratkasu?

2023-08-31 08:36 UTC, Alexander-Tallqvist-Siili commented
@jiisuominen Tuo mikä tuossa näkyy on "Sivun otsikko" -lohko. Kyseisen lohkon asetuksissa on säädetty, että tämä on piilossa sivuilla /application-search ja /application-search/*. Jos viewin polkua on muutetaan, niin lohkon asetuksia täytyy myös säätää. Voin hoitaa.

2023-08-31 10:18 UTC, Alexander-Tallqvist-Siili commented
@jiisuominen Haun osoite muutettu /application-search -> /etsi-avustusta, eli aliaksien kanssa ei tarvitse venkslailla. Myös lohkon asetukset säädetty kuntoon.

2023-08-31 10:22 UTC, jiisuominen approved these changes

2023-08-31 10:37 UTC, merged