feat: AU-1486: Import webform configs from production
City-of-Helsinki/hel-fi-drupal-grants pull request #679
Opened 2023-08-25 19:19 UTC by Puavo

# [AU-1486](https://helsinkisolutionoffice.atlassian.net/browse/AU-1486)

Tämä on vielä keskseneräinen ja lopullinen testaaminen vaatii muutoksia tuotantoon. Nämä saadaan tehtyä ympäristömuuttujilla ja helfi-api-base moduulin avulla.

## What was done

Drush komento

## How to install

* Make sure your instance is up and running on correct branch.
  * `git checkout feature/AU-1486-webform-configs-from-prod`
  * `make fresh`
* Run `make drush-cr`

## How to test

* [ ] Check that this feature works
* [ ] Check that code follows our standards

2023-08-28 05:20 UTC, jiisuominen commented on conf/cmi/user.role.ad_user.yml
>  label: 'AD User'
Miks nää roolien painot muuttuu?

2023-08-28 05:21 UTC, jiisuominen commented on public/modules/custom/grants_webform_import/src/Commands/WebformImportCommands.php
> +    $url = "https://hel-fi-drupal-grant-applications.docker.so/en/jsonapi/webform/webform";
Nää vois laittaa ympäristömuuttujiin ni päästäs testailemaan palvelimilla.

Vois testaa vaik TEST / STAGE ekana

2023-08-28 05:22 UTC, jiisuominen reviewed
Kommentit?

2023-08-28 05:24 UTC, jiisuominen commented on public/modules/custom/grants_webform_import/src/Commands/WebformImportCommands.php
> +    $url = "https://hel-fi-drupal-grant-applications.docker.so/en/jsonapi/webform/webform";
Ja sellanen tuli mieleeni, että tuolla on erilaisia endpointeja, niin palauttaaks tuo kaiken mitä tarvitaan? Myös siis 3rd party settingsit?

2023-08-28 06:08 UTC, Puavo commented on public/modules/custom/grants_webform_import/src/Commands/WebformImportCommands.php
> +    $url = "https://hel-fi-drupal-grant-applications.docker.so/en/jsonapi/webform/webform";
Vertailin json apia ja restiä. Valitsen JSON apin koska se pystyy palauttamaan yhdellä kutsulla kaikki webform configit.

Vertaisin JSON apin palauttamaa dataa siihen mitä samainen moduuli tuottaa luettuaan config-tiedoston. Id:t eivät vastanneet aivan toisiaan kuten koodista voi päätellä. Mutta kaikki webformiin liittyvät config fieldit olivat yhtenevät.

2023-08-28 06:10 UTC, Puavo commented on public/modules/custom/grants_webform_import/src/Commands/WebformImportCommands.php
> +    $url = "https://hel-fi-drupal-grant-applications.docker.so/en/jsonapi/webform/webform";
Tämän voin tehdä mutta autentikaatioita en saanut vielä toimimaan. Halutaanko edetä tämän kanssa ja avata jollain palvelimella configit anonyymeille käyttäjille vai laitetaanko ensin autentikaatio kuntoon?

2023-08-28 06:12 UTC, Puavo commented on conf/cmi/user.role.ad_user.yml
>  label: 'AD User'
Painot vaikuttavat siihen missä järjestyksessä roolit näkyvät esim. tässä listauksessa: https://hel-fi-drupal-grant-applications.docker.so/en/admin/people/roles Uuden roolin lisääminen pudotti muut roolit alemmas.

2023-08-28 09:53 UTC, Puavo commented
Koodin testaaminen lokaalilla.

1. Päivitä Drupal jotta uusi rooli luodaan.

2. Päivitä `local.settings.php`

```
$api_accounts = [
  [
    'username' => 'webform_config_retriever',
    'password' => '3yCgDQvYBvK2tL6E',
    'mail' => 'drupal+webform_config_retriever@hel.fi',
    'roles' => ['json_api_user'],
  ],
];
$config['helfi_api_base.api_accounts']['accounts'] = $api_accounts;
```

3. Aja `drush helfi:post-deploy` Helfi magia luo meille käyttäjän.

4. Lisää `local.settings.php` tiedostoon vielä
```
putenv('GRANTS_WEBFORM_IMPORT_BASE_URL=https://hel-fi-drupal-grant-applications.docker.so');
putenv('GRANTS_WEBFORM_IMPORT_AUTHORIZATION_HEADER=Basic d2ViZm9ybV9jb25maWdfcmV0cmlldmVyOjN5Q2dEUXZZQnZLMnRMNkU=');
```
5. Aja `drush gwia`

2023-08-28 11:47 UTC, Puavo commented
Kohdan kaksi voi korvata serveriympäristöissä lisäämällä ympäristömuuttujan `DRUPAL_API_ACCOUNTS=W3t1c2VybmFtZTp3ZWJmb3JtX2NvbmZpZ19yZXRyaWV2ZXIscGFzc3dvcmQ6M3lDZ0RRdllCdksydEw2RSxyb2xlczpbanNvbl9hcGlfdXNlcl19XQ==`

2023-08-28 13:03 UTC, oskarimysteerio commented
Rajapinta tuntuu toimivan ok:

Ongelmia: Data tulee vain yhdellä kielellä ja oletuksena enkuksi:

![image](https://github.com/City-of-Helsinki/hel-fi-drupal-grants/assets/43133397/bff61807-9833-4dea-a860-c1e042ebdc3f)

Pudottaa kenttiä, näyttää että kaiken näkönen kustomi karkaa

![image](https://github.com/City-of-Helsinki/hel-fi-drupal-grants/assets/43133397/96d4f655-f0d1-483a-af34-e916f726ddb9)
![image](https://github.com/City-of-Helsinki/hel-fi-drupal-grants/assets/43133397/573cf9bd-8170-4b0a-ad42-c49da4aed15c)

![image](https://github.com/City-of-Helsinki/hel-fi-drupal-grants/assets/43133397/97b8b3b9-36d7-4e55-b04f-d83bd4f6c519)
![image](https://github.com/City-of-Helsinki/hel-fi-drupal-grants/assets/43133397/d0b8a72d-5766-4e5d-a1a4-31949af0fd72)

2023-08-28 14:58 UTC, oskarimysteerio commented
Tai sit olin liian innokaana testaamassa noita, jos oli tarkotus vain toi pohja :D

2023-08-29 04:34 UTC, jiisuominen commented on public/modules/custom/grants_webform_import/src/Commands/WebformImportCommands.php
> +    $url = "https://hel-fi-drupal-grant-applications.docker.so/en/jsonapi/webform/webform";
Hyvä hyvä.

2023-08-29 04:46 UTC, jiisuominen commented on conf/cmi/user.role.ad_user.yml
>  label: 'AD User'
Joo mietin vaan siis, että oon opastanu noille tietyn järkän. Loppupeleissä ei oo väliä siis.

2023-08-29 04:48 UTC, jiisuominen commented
> Rajapinta tuntuu toimivan ok:
> 
> Ongelmia: Data tulee vain yhdellä kielellä ja oletuksena enkuksi:

Jaa tuliskohan tästä noi enkuks vaa?
`    $baseUrl = getenv('GRANTS_WEBFORM_IMPORT_BASE_URL');
    // Language parameter does not affect the response.
    $url = $baseUrl . '/en/jsonapi/webform/webform';`

2023-08-29 05:14 UTC, jiisuominen requested changes

2023-08-29 05:14 UTC, jiisuominen commented on public/modules/custom/grants_webform_import/src/Commands/WebformImportCommands.php
> +    $isLocal = str_contains($url, 'hel-fi-drupal-grant-applications.docker.so');
Täs kandeis kyl käyttää jotain muuta tapaa tohon lokaalin määrittelyyn, esim APP_ENV muuttuja tai sit ApplicationHandlerin metodia, joka ois suositeltava tapa.

2023-08-29 06:01 UTC, Puavo commented on public/modules/custom/grants_webform_import/src/Commands/WebformImportCommands.php
> +    $isLocal = str_contains($url, 'hel-fi-drupal-grant-applications.docker.so');
`$isLocal` muuttujan on tarkoitus kertoa onko palvelin jolta kysytään dataa lokaali joten APP_ENV muuttujasta ei ole iloa. Ainakin muuttujan voi nimetä tarkemmin.

2023-08-29 06:04 UTC, Puavo commented
Jos noi kielet eroaa niin sittenhän sitä voisi saada käännökset pelaamaan. Mitäköhän mä olen katsonut kieroon? Mutta mä katson noihin.

2023-08-29 07:31 UTC, jiisuominen commented
`                "third_party_settings": {
                    "grants_metadata": {
                        "applicationTypeSelect": "51",
                        "applicationType": "KASKOYLEIS",
                        "applicationTypeID": "51",
                        "applicationIndustry": "KASKO",
                        "applicantTypes": {
                            "registered_community": "registered_community"
                        },
                        "applicationTypeTerms": {
                            "64": "64",
                            "45": "45",
                            "48": "48"
                        },
                        "applicationTargetGroup": "21",
                        "applicationOpen": "2023-04-03T08:00:00",
                        "applicationClose": "2029-10-06T16:00:00",
                        "applicationContinuous": 0,
                        "disableCopying": 0,
                        "applicationActingYears": {
                            "2023": "2023",
                            "2024": "2024",
                            "2025": "2025"
                        },
                        "applicationActingYearsType": "fixed",
                        "applicationActingYearsNextCount": ""
                    }
                },`

2023-08-30 06:08 UTC, jiisuominen reviewed
![image](https://github.com/City-of-Helsinki/hel-fi-drupal-grants/assets/892920/f42ff8c1-561f-40d3-aac0-507407298236)

Saan kirjautumatta kuitenkin jsonapi dataa tuolta endpointista, ja vaikka mitään näy, niin oisko kuitenki ton palautettava 403?

2023-08-31 11:09 UTC, Puavo commented
Nyt drupal palauttaa json api routeille 403 ellei käyttäjällä ole oikeaa roolia.

2023-09-01 11:55 UTC, oskarimysteerio approved these changes

2023-09-05 11:39 UTC, merged