fix: AU-1473: Fix headers in grey box on page 1 of applications
City-of-Helsinki/hel-fi-drupal-grants pull request #704
Opened 2023-09-04 13:27 UTC by strangeworlder

# [AU-1473](https://helsinkisolutionoffice.atlassian.net/browse/AU-1473)

## What was done

* On page 1 of forms there was a H2 with the title "Hakijan tiedot" that had a H3 inside it with the title "Hakijan tiedot" with a fieldset inside it with the legend "Hakijan tiedot". These were changed to different names
* The H3 inside the grey box was 33% wide, it is now of proper size.

## How to install

* Make sure your instance is up and running on correct branch.
  * `git checkout feature/AU-1473-grey-box`
  * `make fresh`
* Run `make drush-cr`

## How to test

* [ ] See that the headline in the grey box, if it was "hakijan tiedot" is now "haetut tiedot"
* [ ] Check that code follows our standards

## Designers review

* [ ] This PR does not need designers review
* [ ] This PR has been visually reviewed by a designer (Name of the designer)

## Other PRs

* Link to other PR

2023-09-05 05:40 UTC, suvikankare requested changes

2023-09-05 05:40 UTC, suvikankare commented on conf/cmi/language/en/webform.webform.kasko_ip_lisa.yml
Oisko nää kuitenkin retrieved?

2023-09-05 06:14 UTC, strangeworlder commented on conf/cmi/language/en/webform.webform.kasko_ip_lisa.yml
Vois olla :D

2023-09-06 06:40 UTC, strangeworlder commented on conf/cmi/language/en/webform.webform.kasko_ip_lisa.yml
Fix'd

2023-09-06 06:40 UTC, strangeworlder commented
typo fiksattu @suvikankare

2023-09-06 09:54 UTC, suvikankare approved these changes

2023-09-06 11:40 UTC, merged