feat: AU-1265: Switch logic for removing bank account confirmation file
City-of-Helsinki/hel-fi-drupal-grants pull request #714
Opened 2023-09-08 09:36 UTC by Puavo

# [AU-1265](https://helsinkisolutionoffice.atlassian.net/browse/AU-1265)

Aiemmin oli mahdollista poistaa pankkitilin varmistusliite poistamatta itse tiliä.

## What was done

Pankkitiliä poistaessa otetaan tiedoston nimi talteen ja varsinainen poisto tehdään vasta kun lomake lähetetään.

## How to install

* Make sure your instance is up and running on correct branch.
  * `git feature/AU-1265-confirmation-file-removing`
  * `make fresh`
* Run `make drush-cr`

## How to test

* [ ] Kirjaudu rekisteröityneenä yhteisönä.
* [ ] Mene profiilin muokkauslomakkeelle ja varmista että logiikka toimii

2023-09-11 11:41 UTC, jiisuominen requested changes

2023-09-11 11:41 UTC, jiisuominen commented on public/modules/custom/grants_profile/src/Form/GrantsProfileFormBase.php
> +    $attachments = $form_state->get('attachments_to_remove');
tästä tulee virhe:
`The website encountered an unexpected error. Please try again later.
Error: Call to a member function get() on null in Drupal\grants_profile\Form\GrantsProfileFormBase::removeAttachments() (line 271 of modules/custom/grants_profile/src/Form/GrantsProfileFormBase.php).`

näköjään toi formi väärin nimetty vaan. mut mä yritän saada nää pr:t selvittyä ni joudut ite fiksaa.

2023-10-16 12:27 UTC, oskarimysteerio commented
Tää varmaan tällä hetkellä ottaa kantaan vaan Rekisteröityneiden yhteisöjen liitteiden poistoon? Pitäis varmaan tunkata noihin Toimintaryhmä - ja yksityishenkilölomakkeille?

2023-10-17 08:03 UTC, oskarimysteerio commented
Lisäsin Unregistered & Private person formeihin kanssa nää.

2023-10-23 07:55 UTC, oskarimysteerio commented
En tiedä pitäiskö tätä ootella, että toi profiilin refaktorointi on kunnossa, niin pääsee siitä korjaamaan merge konfliktit ja duplikaatiot pois

2023-10-24 04:30 UTC, jiisuominen commented
Varmaan hyvä idis. Laitan draftiks ni ei häiriköi tolla listalla.

2023-10-25 12:42 UTC, oskarimysteerio commented
Korjasin mergekonfliktit ton profiili refaktroinnin jäljiltä

2023-10-26 05:25 UTC, jiisuominen approved these changes

2023-10-27 08:18 UTC, merged