fix: AU-1612: Implement end date restriction logic to various form fields
City-of-Helsinki/hel-fi-drupal-grants pull request #793
Opened 2023-09-27 13:15 UTC by Alexander-Tallqvist-Siili

# [AU-1612](https://helsinkisolutionoffice.atlassian.net/browse/AU-1612)

## What was done
TBD.

## How to install

Make sure your instance is up and running on the correct branch.
  * `git checkout fix/AU-1636-profile-page-fix`
  * `make fresh`
  * `make drush-cr`

## How to test
TBD.

2023-10-02 07:52 UTC, jiisuominen approved these changes

2023-10-02 12:52 UTC, oskarimysteerio requested changes
Toiminnallisuus toimii omien testien mukaan niin kuin pitää. 

Tuli vain mieleen, kun meillä on tulossa toi versiointi systeemi ehkä joskus toivottavasti käyttöön, niin noi lomake id:t voi muuttuu erilaisiksi, niin [link](https://github.com/City-of-Helsinki/hel-fi-drupal-grants/pull/793/files#diff-854181244dcd138a1b27e92dde5dbd5cc86f6085e63c1f298aa761e14b5272faR511-R515) & [link](https://github.com/City-of-Helsinki/hel-fi-drupal-grants/pull/793/files#diff-2d14da33bb508516d87a83794b5dc44a9ec033f3fc8acc549aa0f17c64c23944R23-R41) tämänkaltaiset asiat saattaa helposti jäädä päivittämättä. Oliskohan näihin mahdollista kaivaa se lomakkeen application_type id (esim numero `48` tai string `KUVAPROJ`) yms, niin olis ehkä mahdollisesti "future-proof" 

Laitan tän nyt "Changes request" tilaan, ku testailtiin aamulla noita reviewer juttuja tällä pullarilla, tän voi merkata resolvatuks, jos tullaan johonkin aatoksiin tai päätetään myöhemmin muokata noi kuntoon.

2023-10-03 04:39 UTC, jiisuominen commented
> Tuli vain mieleen, kun meillä on tulossa toi versiointi systeemi ehkä joskus toivottavasti käyttöön, niin noi lomake id:t voi muuttuu erilaisiksi, niin [link](https://github.com/City-of-Helsinki/hel-fi-drupal-grants/pull/793/files#diff-854181244dcd138a1b27e92dde5dbd5cc86f6085e63c1f298aa761e14b5272faR511-R515) & [link](https://github.com/City-of-Helsinki/hel-fi-drupal-grants/pull/793/files#diff-2d14da33bb508516d87a83794b5dc44a9ec033f3fc8acc549aa0f17c64c23944R23-R41) tämänkaltaiset asiat saattaa helposti jäädä päivittämättä. Oliskohan näihin mahdollista kaivaa se lomakkeen application_type id (esim numero `48` tai string `KUVAPROJ`) yms, niin olis ehkä mahdollisesti "future-proof"

Joo nää ois kova jos ei tarttis murehtia ollenkaan jatkossa. Noi id:t on parannus, mut oiskohan järkevää / mahdollista jopa kattoo jotain noiden kenttien olemassaolo jossain metodissa?

` const webformIdDateFieldMap = {
        'liikunta_tapahtuma': {
          'start_date_field': 'edit-alkaa',
          'end_date_field': 'edit-paattyy',
        },
        'nuorisotoiminta_projektiavustush': {
          'start_date_field': 'edit-projekti-alkaa',
          'end_date_field': 'edit-projekti-loppuu',
        },
        'kasko_ip_lisa': {
          'start_date_field': 'edit-alkaen',
          'end_date_field': 'edit-paattyy',
        },
        'kuva_projekti': {
          'start_date_field': 'edit-hanke-alkaa',
          'end_date_field': 'edit-hanke-loppuu',
        },
        'taide_ja_kulttuuri_kehittamisavu': {
          'start_date_field': 'edit-hanke-alkaa',
          'end_date_field': 'edit-hanke-loppuu',
        }
      };`

no en nyt tiiä onks noihin jotain sääntöä mahista keksiä. Jos on *_alkaa / *_alkaen JA *_loppuu / *_päättyy?

En tiiä.

2023-10-04 12:44 UTC, Alexander-Tallqvist-Siili commented
@jiisuominen @oskarimysteerio Teen tämän nyt mielummin tuolla Oskarin ehdottamalla tavalla - kuulostaa ainakin omaan korvaan kestävämmältä ratkaisulta.

2023-10-05 05:21 UTC, jiisuominen approved these changes
Hitto mä haluisin vieläki nähä tän jotenki dynaamisempana, noi kovakoodaukset aina vähän tökkii.

Mut ehkä tähän on käytetty riittävästi paukkuja nyt, katotaa jos tulee eteen tulevaisuudessa jos tekis toisella tavalla..

2023-10-05 05:22 UTC, merged