AU-1732: Add tests for profile page
City-of-Helsinki/hel-fi-drupal-grants pull request #857
Opened 2023-10-13 12:59 UTC by roope-ankka

# [AU-1732](https://helsinkisolutionoffice.atlassian.net/browse/AU-1732)

This commits adds E2E tests for the profile page

## What was done

* This thing was fixed

## How to install

* Make sure your instance is up and running on correct branch.
  * `git checkout feauture/AU-1732`
* Run `make test-pw my_services`

## How to test

* [ ] Check that this feature works
* [ ] Check that code follows our standards

2023-10-16 12:13 UTC, oskarimysteerio commented
Vähän hämäs kun pitikin olla jo tietoja noissa profiileissa että nää toimii, varmaan hyvä jatkossa mainita tai sitten pitää jotenkin jumpata, et nää tulis automaagisesti.

Muutamat errorit tuli omassa päässä. 
![image](https://github.com/City-of-Helsinki/hel-fi-drupal-grants/assets/43133397/f28a01bc-d851-404e-a58d-a47658d054e7)
1. Jonkun takia enkuksi muutama asia tossa omat tiedot osioissa (Tein tiksun https://helsinkisolutionoffice.atlassian.net/browse/AU-1753)
2. Jonkun takia liitteen poistaminen kaatuu kanssa, pitää ihmetellä onko joku ympäristöjuttu vai löydettiinkö vahingossa toinen bugi

tl:dr; ehkä testit löys jo jotain ongelmia :o ?

2023-10-17 09:41 UTC, jiisuominen submitted a review, later dismissed
![image](https://github.com/City-of-Helsinki/hel-fi-drupal-grants/assets/892920/6a36398f-abbb-4711-a22d-afa7b9e4c630)
![image](https://github.com/City-of-Helsinki/hel-fi-drupal-grants/assets/892920/c7178065-0ddb-486d-9cea-3a0170326d12)
![image](https://github.com/City-of-Helsinki/hel-fi-drupal-grants/assets/892920/6ae40097-34aa-4ac8-a376-21634eeadaa0)

Mullaki feilaa testit jotenki omituisesti.

2023-10-26 06:33 UTC, roope-ankka commented
> Mullaki feilaa testit jotenki omituisesti.

@oskarimysteerio @jiisuominen --> Näiden testien alussa on nyt ATV-nollaus ja hakijaprofiilien luonti, toivotaan että nyt menee testit läpi

2023-10-30 13:29 UTC, roope-ankka commented
> 
> Mullaki feilaa testit jotenki omituisesti.


Nyt voi yrittää ajaa testit taas. Vasten hyviä käytäntöjä jouduin laittamaan `await page.waitForTimeout(1000)` tonne filujen uploadaukseen, mutta omalla koneella se tuotti kohtuullisia parannuksia testien feilaukseen.

2023-11-01 12:01 UTC, jiisuominen requested changes
[playwright-report.zip](https://github.com/City-of-Helsinki/hel-fi-drupal-grants/files/13226616/playwright-report.zip)

Vieläkin feilaa pankkitilin lisäykseen:
`  3 failed
    [logged-in] › my_services.spec.ts:98:13 › hakuprofiili › private person › a bank account is required
    [logged-in] › my_services.spec.ts:163:13 › hakuprofiili › registered community › a bank account is required
    [logged-in] › my_services.spec.ts:272:13 › hakuprofiili › unregistered community › a bank account is required`

2023-11-01 12:03 UTC, oskarimysteerio commented
`await expect(page.getByText("Tilinumero ja vahvistusliite poistettiin")).toBeVisible()`

Tohon pankkitili poistoon tuli mieleen, et tota viestiä ei välttämättä tuu enään tos kohtaan, ku se poistaminen refaktoroitiin, niin voisko se vaikuttaa asiaan.

2023-11-01 12:26 UTC, roope-ankka commented
> `await expect(page.getByText("Tilinumero ja vahvistusliite poistettiin")).toBeVisible()`
> 
> Tohon pankkitili poistoon tuli mieleen, et tota viestiä ei välttämättä tuu enään tos kohtaan, ku se poistaminen refaktoroitiin, niin voisko se vaikuttaa asiaan.

Joo, näin on. Tää on nyt korjattu. @jiisuominen

2023-11-02 05:17 UTC, jiisuominen approved these changes

2023-11-02 11:30 UTC, jiisuominen approved these changes

2023-11-02 11:35 UTC, merged