AU-1734: Add tests to Oma Asiointi page
City-of-Helsinki/hel-fi-drupal-grants pull request #858
Opened 2023-10-13 13:02 UTC by roope-ankka

# [AU-1734](https://helsinkisolutionoffice.atlassian.net/browse/AU-1734)

## What was done

* Added E2E tests for the "Oma asiointi" page

## How to install

* Make sure your instance is up and running on correct branch.
  * `git checkout feature/AU-1734`
* Run `make test-pw my_services`

## How to test

* [ ] Check that this feature works
* [ ] Check that code follows our standards

2023-10-18 04:51 UTC, jiisuominen requested changes
![image](https://github.com/City-of-Helsinki/hel-fi-drupal-grants/assets/892920/0068ba85-baf5-4965-a002-d9c6162cb603)
Osoitteen testissä jotain epäselvää vielä.

Html raporttityyppi ei tallenna html raporttia ainakaan projektin kansioon kuten hostilla ajaessa.
`  Serving HTML report at http://localhost:9323. Press Ctrl+C to quit.`
Tuon se näyttää mutta ei aukea localhostista tuo kun kontissa ajetaan. Ei tarvis ku kaivaa jostain tolle html muotoiselle raportille tallennuspaikka.

`npx playwright show-report`
 ^ näyttää olemassaolevan raportin, tää sanoo nyt `No report found at "/app/e2e/playwright-report"`

2023-10-18 04:52 UTC, jiisuominen commented
Ja sit jos viitit nimetä nää branchit vielä [ton ohjeen](https://helsinkisolutionoffice.atlassian.net/wiki/spaces/KAN/pages/8201044258/Kehitysty+kalut+-metodit+ja+palvelut#Kehityshaarat) mukaisesti ni ois jepa.

`git flow feature start AU-XX-short-description-of-feature`

2023-10-18 04:57 UTC, jiisuominen commented
Komento takasin html raporttien osalta. Ilmeisesti toi PHPSTORM jotenki lägittää minuutteja perässä ja nyt näin ku näinkin raportin: 
[playwright-report.zip](https://github.com/City-of-Helsinki/hel-fi-drupal-grants/files/12984714/playwright-report.zip)

2023-10-18 07:16 UTC, roope-ankka commented
> `npx playwright show-report` ^ näyttää olemassaolevan raportin, tää sanoo nyt `No report found at "/app/e2e/playwright-report"`

Ton komennon pystyy ajamaan e2e hakemistossa, koititko sieltä käsin?

2023-10-18 07:17 UTC, roope-ankka commented
> Ja sit jos viitit nimetä nää branchit vielä [ton ohjeen](https://helsinkisolutionoffice.atlassian.net/wiki/spaces/KAN/pages/8201044258/Kehitysty+kalut+-metodit+ja+palvelut#Kehityshaarat) mukaisesti ni ois jepa.
> 
> `git flow feature start AU-XX-short-description-of-feature`

Joo, ups... Pystyyköhän tän PR:n branchi nimeä muuttaa jälkikäteen? Vai luonko uuden pullarin oikeanlaisella nimellä?

2023-10-19 08:36 UTC, jiisuominen commented
> > Ja sit jos viitit nimetä nää branchit vielä [ton ohjeen](https://helsinkisolutionoffice.atlassian.net/wiki/spaces/KAN/pages/8201044258/Kehitysty+kalut+-metodit+ja+palvelut#Kehityshaarat) mukaisesti ni ois jepa.
> > `git flow feature start AU-XX-short-description-of-feature`
> 
> Joo, ups... Pystyyköhän tän PR:n branchi nimeä muuttaa jälkikäteen? Vai luonko uuden pullarin oikeanlaisella nimellä?

Ei oo sen arvosta. Jatkossa vaa ni löytyy iisimmin.

2023-10-26 06:35 UTC, closed without merging