AU-1690: Modify env cleaning script
City-of-Helsinki/hel-fi-drupal-grants pull request #859
Opened 2023-10-13 13:06 UTC by roope-ankka

# [AU-1690](https://helsinkisolutionoffice.atlassian.net/browse/AU-1690)

Modified the `clean-env-for-testing.sh` script to output the deleted document IDs to a file.

**NOTE**: Currently doesn't delete anything (WIP)

## How to install

* Make sure your instance is up and running on correct branch.
  * `git checkout feature/AU-1690`

* Run the `clean-env-for-testing.sh` script

## How to test

* [ ] Check that this feature works
* [ ] Check that code follows our standards

2023-10-18 05:43 UTC, jiisuominen requested changes
Tää jää ikuiseen luuppiin:

`UUID RESULTS: 0
./clean-env-for-testing.sh: line 60: jq: command not found
./clean-env-for-testing.sh: line 27: jq: command not found
UUID RESULTS: 0
./clean-env-for-testing.sh: line 60: jq: command not found
./clean-env-for-testing.sh: line 27: jq: command not found
UUID RESULTS: 0
./clean-env-for-testing.sh: line 60: jq: command not found
./clean-env-for-testing.sh: line 27: jq: command not found
UUID RESULTS: 0
./clean-env-for-testing.sh: line 60: jq: command not found
./clean-env-for-testing.sh: line 27: jq: command not found
UUID RESULTS: 0
./clean-env-for-testing.sh: line 60: jq: command not found
./clean-env-for-testing.sh: line 27: jq: command not found
UUID RESULTS: 0
./clean-env-for-testing.sh: line 60: jq: command not found
./clean-env-for-testing.sh: line 27: jq: command not found
UUID RESULTS: 0
./clean-env-for-testing.sh: line 60: jq: command not found
./clean-env-for-testing.sh: line 27: jq: command not found
UUID RESULTS: 0
./clean-env-for-testing.sh: line 60: jq: command not found
./clean-env-for-testing.sh: line 27: jq: command not found
UUID RESULTS: 0
./clean-env-for-testing.sh: line 60: jq: command not found
./clean-env-for-testing.sh: line 27: jq: command not found
UUID RESULTS: 0`

2023-10-18 07:13 UTC, roope-ankka commented
> Tää jää ikuiseen luuppiin:
> 
> `UUID RESULTS: 0 ./clean-env-for-testing.sh: line 60: jq: command not found ./`

Tätä varten pitää asentaa [jq](https://jqlang.github.io/jq/) (joka oli käytössä alkuperäsessä skriptissä)

2023-10-18 07:56 UTC, oskarimysteerio requested changes
Joo, toimii oletetusti mulla, kunhan on asennettuna toi `jq`.

Noi poistetut lista tulee nyt ATV dokumentin ID:n mukaan, kun halutaan hakemustunnukset (transaction_id) (LOCALO-XX-XXXXXXX).

Varmaan pitää ottaa huomioon noi profiilit mitkä poistuu kanssa, kun niitä tuskin tarvitsee minnekkää lähetellä, että on poistettu

![image](https://github.com/City-of-Helsinki/hel-fi-drupal-grants/assets/43133397/8a9cd013-1d00-4582-9844-b1ce7160edbe)

2023-10-18 09:33 UTC, roope-ankka commented
> Noi poistetut lista tulee nyt ATV dokumentin ID:n mukaan, kun halutaan hakemustunnukset (transaction_id) (LOCALO-XX-XXXXXXX).
> 
> Varmaan pitää ottaa huomioon noi profiilit mitkä poistuu kanssa, kun niitä tuskin tarvitsee minnekkää lähetellä, että on poistettu
> 

Tää on nyt fiksattu, tiedostoon kirjoitetaan nyt `transaction_id`. Lisäsin kans skriptiin ehdon että jos kyseessä on `grants_profile` niin skipataan DELETE operaatio, tässä kuitenkin pitäisi poistaa vaan hakemuksia

2023-10-19 08:33 UTC, jiisuominen commented
Siis mitäs ihmettä. Ilmeisesti toi oli mäkissä boksista suoraan ku en mä mitään asennellu ku ton alkuperäsen tein.

Ei kyllä huvita mitään alkaa tässä kääntelemään, eikä se nyt varmaan oo tarkotuksenmukastakaan.

Pitäsköhän toiki laittaa Dockeriin ni toimis ilman sen kummempia asennuksia?

En nyt voi pyytää uudestaan muutoksia ni pitää tägätä vaa: @roope-ankka

2023-10-24 09:20 UTC, roope-ankka commented on tools/clean-env-for-testing.sh
> +        fi
Tässä korjaus siihen mikä ID printataan tiedostoon @oskarimysteerio

2023-10-24 09:28 UTC, roope-ankka commented on tools/clean-env-for-testing.sh
>          else
@oskarimysteerio Tässä modikset

- Kirjoitetaan tiedostoon ID:n sijaan transaction_id
- Skipataan grant_profileitten kirjoittaminen tiedostoon

2023-10-24 12:45 UTC, jiisuominen submitted a review, later dismissed
Multa saletisti jääny johonki roikkumaan 3 kommenttia..

2023-10-24 12:51 UTC, roope-ankka commented on e2e/tests/public/frontpage.spec.ts
> -test('verify info block', async ({ page }) => {
Totta, poistettu

2023-10-24 12:58 UTC, jiisuominen approved these changes

2023-10-24 13:03 UTC, merged