Feature/au 1760 liikunta tilankaytto
City-of-Helsinki/hel-fi-drupal-grants pull request #892
Opened 2023-10-24 11:00 UTC by suvikankare

## What was done

* [AU-1760](https://helsinkisolutionoffice.atlassian.net/browse/AU-1760) Aktiiviharrastajat as required
* [AU-1761](https://helsinkisolutionoffice.atlassian.net/browse/AU-1761) Update attachment text
* [AU-1763](https://helsinkisolutionoffice.atlassian.net/browse/AU-1763) 
  1. Re-style Lajijaostot
  2. Laji required 
  3. At least one of the age groups required
  4. Reordered fields to men - women - others
* [AU-1773](https://helsinkisolutionoffice.atlassian.net/browse/AU-1773) Hide fieldset Jäsenet
* [AU-1794](https://helsinkisolutionoffice.atlassian.net/browse/AU-1794) Change term 'Subsidy for use of space' to 'Facility usage grant'

## How to install

* Make sure your instance is up and running on correct branch.
  * `git checkout feature/AU-1760-liikunta-tilankaytto`
  * `make fresh`
* Run `make drush-cr`

## How to test

* [ ] [Open application](https://hel-fi-drupal-grant-applications.docker.so/fi/uusi-hakemus/liikunta_toiminta_ja_tilankaytto)
* [ ] Go through "What was done" and check that everything works

2023-10-25 05:48 UTC, jiisuominen commented
> SonarCloud Quality Gate failed.    [![Quality Gate failed](https://camo.githubusercontent.com/4ea51c1f64ee3746f631653a02ab678ca6a3efb5f5cb474402faed2e3dcf90b5/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f5175616c6974794761746542616467652f6661696c65642d313670782e706e67)](https://sonarcloud.io/dashboard?id=City-of-Helsinki_avustusasiointi&pullRequest=892)
> 
> [![Bug](https://camo.githubusercontent.com/4c6102327f5a954f9c8acaf2e2714183157a9e41717b371b2cd585cf25057310/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f6275672d313670782e706e67)](https://sonarcloud.io/project/issues?id=City-of-Helsinki_avustusasiointi&pullRequest=892&resolved=false&types=BUG) [![A](https://camo.githubusercontent.com/1cba125a897d7fa47033a3b3b2be2bbee680d34d4f004a215564659b853fb201/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f526174696e6742616467652f412d313670782e706e67)](https://sonarcloud.io/project/issues?id=City-of-Helsinki_avustusasiointi&pullRequest=892&resolved=false&types=BUG) [0 Bugs](https://sonarcloud.io/project/issues?id=City-of-Helsinki_avustusasiointi&pullRequest=892&resolved=false&types=BUG) [![Vulnerability](https://camo.githubusercontent.com/3ba1ee49636ffc3427e38649a9f8a65ee392f28e8a662fcf96ce24cefbb520e9/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f76756c6e65726162696c6974792d313670782e706e67)](https://sonarcloud.io/project/issues?id=City-of-Helsinki_avustusasiointi&pullRequest=892&resolved=false&types=VULNERABILITY) [![A](https://camo.githubusercontent.com/1cba125a897d7fa47033a3b3b2be2bbee680d34d4f004a215564659b853fb201/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f526174696e6742616467652f412d313670782e706e67)](https://sonarcloud.io/project/issues?id=City-of-Helsinki_avustusasiointi&pullRequest=892&resolved=false&types=VULNERABILITY) [0 Vulnerabilities](https://sonarcloud.io/project/issues?id=City-of-Helsinki_avustusasiointi&pullRequest=892&resolved=false&types=VULNERABILITY) [![Security Hotspot](https://camo.githubusercontent.com/fb735cbe76f8d5e1679c76ce83b740ceb1eaf62de4f7bf88623dc9953261aff7/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f73656375726974795f686f7473706f742d313670782e706e67)](https://sonarcloud.io/project/security_hotspots?id=City-of-Helsinki_avustusasiointi&pullRequest=892&resolved=false&types=SECURITY_HOTSPOT) [![A](https://camo.githubusercontent.com/1cba125a897d7fa47033a3b3b2be2bbee680d34d4f004a215564659b853fb201/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f526174696e6742616467652f412d313670782e706e67)](https://sonarcloud.io/project/security_hotspots?id=City-of-Helsinki_avustusasiointi&pullRequest=892&resolved=false&types=SECURITY_HOTSPOT) [0 Security Hotspots](https://sonarcloud.io/project/security_hotspots?id=City-of-Helsinki_avustusasiointi&pullRequest=892&resolved=false&types=SECURITY_HOTSPOT) [![Code Smell](https://camo.githubusercontent.com/8fe18b2dfb6f7d4e44582f281b29f617eb5ae07c248d2002ca586e91da219212/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f636f64655f736d656c6c2d313670782e706e67)](https://sonarcloud.io/project/issues?id=City-of-Helsinki_avustusasiointi&pullRequest=892&resolved=false&types=CODE_SMELL) [![A](https://camo.githubusercontent.com/1cba125a897d7fa47033a3b3b2be2bbee680d34d4f004a215564659b853fb201/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f526174696e6742616467652f412d313670782e706e67)](https://sonarcloud.io/project/issues?id=City-of-Helsinki_avustusasiointi&pullRequest=892&resolved=false&types=CODE_SMELL) [4 Code Smells](https://sonarcloud.io/project/issues?id=City-of-Helsinki_avustusasiointi&pullRequest=892&resolved=false&types=CODE_SMELL)
> 
> [![No Coverage information](https://camo.githubusercontent.com/86785eaa572e061f5ecb3f8bf1cbb7b8eca44925083f92d067805b4362cead0c/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f436f76657261676543686172742f4e6f436f766572616765496e666f2d313670782e706e67)](https://sonarcloud.io/component_measures?id=City-of-Helsinki_avustusasiointi&pullRequest=892) No Coverage information [![19.0%](https://camo.githubusercontent.com/efef8d7f6abcfdf5c67f93cc5bf65fa6c176ccbc2b89d16309748853e95b3863/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f4475706c69636174696f6e732f32302d313670782e706e67)](https://sonarcloud.io/component_measures?id=City-of-Helsinki_avustusasiointi&pullRequest=892&metric=new_duplicated_lines_density&view=list) [19.0% Duplication](https://sonarcloud.io/component_measures?id=City-of-Helsinki_avustusasiointi&pullRequest=892&metric=new_duplicated_lines_density&view=list)
> 
> ![idea](https://camo.githubusercontent.com/00150338e138e454e357462ed3d9cfceaf338ca50ccadcc1f3a75ad6a0e2aab2/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f6c696768745f62756c622d313670782e706e67) Catch issues before they fail your Quality Gate with our IDE extension ![sonarlint](https://camo.githubusercontent.com/e4a8f808c72d84f231c1400ce7f2c77a09afe3eadb6bde9ad2c208a46735d320/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f736f6e61726c696e742d313670782e706e67) [SonarLint](https://www.sonarsource.com/products/sonarlint/features/connected-mode/?referrer=sonarcloud-welcome)

Oon nostanu ton koodikopioinnin -> 30% tän tsekin jälkeen. Uus kommitti varmasti ratkasee sen.

2023-10-25 06:21 UTC, oskarimysteerio commented
Olikohan "Myös yksi ikäluokka on pakollinen.", että pitää olla joko Senioireita / Adult / Junior vai että jokaisessa groupissa pitää olla 1 arvo 🤔

2023-10-25 06:23 UTC, oskarimysteerio commented on conf/cmi/webform.webform.liikunta_toiminta_ja_tilankaytto.yml
> +    applicationClose: '2024-02-29T11:19:00'
Tää vissiin valunu lokaalin yliajoista?

2023-10-27 11:46 UTC, oskarimysteerio commented on public/modules/custom/grants_club_section/src/Validator/FieldValueValidator.php
> +    if (!empty($parent['senioMen']) || !empty($parent['seniorWomen']) || !empty($parent['seniorOthers'])) {
Täst puuttu r
```suggestion
    if (!empty($parent['seniorMen']) || !empty($parent['seniorWomen']) || !empty($parent['seniorOthers'])) {
```

2023-10-27 11:58 UTC, oskarimysteerio requested changes

2023-10-27 11:58 UTC, oskarimysteerio commented on public/modules/custom/grants_club_section/src/Validator/FieldValueValidator.php
> +    if (!empty($parent['men']) || !empty($parent['women']) || !empty($parent['adultOthers'])) {
Eiks tää oo vähän hassusti, jos joku ei oo tyhjä, niin lyödään virhe 😅 ? 

![image](https://github.com/City-of-Helsinki/hel-fi-drupal-grants/assets/43133397/3ff00358-67be-40cd-83fb-9cabd53d620c)

2023-10-30 07:11 UTC, oskarimysteerio commented on public/modules/custom/grants_club_section/src/Validator/FieldValueValidator.php
> +    $sfmnf = $element;
```suggestion
```

2023-10-30 08:18 UTC, oskarimysteerio commented
Niin joo - falskaa viel nää Adult ja Junior validaatiot viel - my bad kun en merkannu jokasen kohalla tota virhettä

![image](https://github.com/City-of-Helsinki/hel-fi-drupal-grants/assets/43133397/b067654f-d4ce-416d-b10a-8c86e33b607c)

2023-10-30 08:22 UTC, oskarimysteerio commented
Varmaan jossain vaihees tulee sanomista, mutta pitäiskö tällä preview sivullea ottaa jotain kantaa, kun noi jäsenet fieldset piilotettiin, nyt sinne tulee "haamuna" noi piilotetut?

![image](https://github.com/City-of-Helsinki/hel-fi-drupal-grants/assets/43133397/b43ebdf0-4f5b-4192-95b1-73f630c00e50)

2023-10-30 10:24 UTC, oskarimysteerio submitted a review, later dismissed
Joo, eiköhän tässä oo punnerrettu tää nyt timanttiseks 😅

2023-10-30 10:28 UTC, oskarimysteerio approved these changes
Tai siis nyt.

2023-10-30 10:40 UTC, merged