test: AU-1834: Add tests for incomplete data
City-of-Helsinki/hel-fi-drupal-grants pull request #911
Opened 2023-11-01 13:17 UTC by Puavo

# [AU-1834](https://helsinkisolutionoffice.atlassian.net/browse/AU-1834)

Lisää testitapaus jossa jsonpath ei ole määritysten mukainen

## What was done

* Luo DataDefinition Luokka jossa on määrittelyt.
* Tämä lisää ATV Scheman code coveragea

## How to install

* Make sure your instance is up and running on correct branch.
  * `git checkout AU-801-tests-with-failing-data-definiotions`
  * `make fresh`
* Run `make drush-cr`

## How to test

* [ ] Aja testit README:n ohjeiden mukaisesti

2023-11-01 13:19 UTC, Puavo commented
Git historia on menossa aika rumaksi mutta voin korjata sen myöhemmin. Se ei vaikuta muihin muutoksiin.

2023-11-06 12:47 UTC, Alexander-Tallqvist-Siili commented
@Puavo Testit tuntuu menevän läpi ja ilmeisesti toimii. Jatkon kannalta näissä testi-tiksuissa vois vähän yrittää avata mitä code-coveragea näihin on lisätty. Mä nyt en ainakaan löytänyt muuta kun tätä. Menikö joku ohi?

![Screenshot 2023-11-06 at 14 45 28](https://github.com/City-of-Helsinki/hel-fi-drupal-grants/assets/117807015/37c97d60-343e-4e2d-8e58-1486f39de3a5)

2023-11-08 07:11 UTC, Alexander-Tallqvist-Siili commented
@Puavo Joo, sori, oon postannut väärän screenshotin. Kysmys kuuluu siis: Oliko tuota code coveragea tullut muualle lisää kun tuohon switch-lausekkeen default caseen?

2023-11-08 07:31 UTC, Puavo commented
Ei tainnut tulla muita muutoksia code coverageen.

2023-11-08 07:33 UTC, Puavo commented
Sonarlintin virheet tulevat ATVSchema luokasta, jonka uudelleenkirjoitus on jo työn alla joten en käyttäisi niihin aikaa tässä yhtyedessä.

2023-11-08 07:34 UTC, Alexander-Tallqvist-Siili submitted a review, later dismissed

2023-11-09 06:11 UTC, jiisuominen commented
> Sonarlintin virheet tulevat ATVSchema luokasta, jonka uudelleenkirjoitus on jo työn alla joten en käyttäisi niihin aikaa tässä yhtyedessä.

PHPCS ainaki vois korjata?

2023-11-10 06:37 UTC, jiisuominen requested changes
Joo muuta tän branchin nimi, toi AU-801 sekottaa huolella ku toi on mergetty joskus 3kk sit

2023-11-10 07:21 UTC, Puavo commented
Tämä PR on korvattu paremmin nimetyllä https://github.com/City-of-Helsinki/hel-fi-drupal-grants/pull/947 jotta releaset ovat paremmin dokumentoitu.

2023-11-10 07:21 UTC, closed without merging