fix: AU-1827: fix kasko toiminta-avustus names
City-of-Helsinki/hel-fi-drupal-grants pull request #917
Opened 2023-11-02 10:40 UTC by suvikankare

# [AU-1827](https://helsinkisolutionoffice.atlassian.net/browse/AU-1827)

## What was done

* Fix kasko toiminta-avustushakemus title translations

## How to install

* Make sure your instance is up and running on correct branch.
  * `git checkout feature/AU-1827-kasko-translations`
  * `make fresh`
* Run `make drush-cr`

## How to test

* [ ] [Open application](https://hel-fi-drupal-grant-applications.docker.so/fi/uusi-hakemus/kasvatus_ja_koulutus_toiminta_av)
* [ ] Check that title translations are correct

2023-11-03 08:18 UTC, strangeworlder requested changes

2023-11-03 08:18 UTC, strangeworlder commented on conf/cmi/language/sv/webform.webform.kasvatus_ja_koulutus_toiminta_av.yml
>  description: 'MVP-f&ouml;rm'
Tän descriptionin voisi vielä napata täältä pois. Mä en tiedä mistä näitä edelleen valuu tänne (tai siis tiedän, kopioidaan miettimättä mitä kopioidaan)

2023-11-06 05:58 UTC, jiisuominen approved these changes

2023-11-06 10:27 UTC, strangeworlder approved these changes

2023-11-06 10:29 UTC, merged