fix: AU-1789: Show additional information data in print view
City-of-Helsinki/hel-fi-drupal-grants pull request #931
Opened 2023-11-03 22:20 UTC by Puavo

# [AU-1789](https://helsinkisolutionoffice.atlassian.net/browse/AU-1789)

Näytä lisätiedot hakemusta tulostaessa

## What was done

Tee lisätietoja varten oma paikka tulostusnäkymään huolehtien että data on käyttökelpoista ilman riippuvuuksia webformiin.

## How to install

* Make sure your instance is up and running on correct branch.
  * `git checkout feature/AU-1789-additional-information-in-print`
  * `make fresh`
* Run `make drush-cr`

## How to test

* [ ] Täytä hakemuksessa lisätiedot kenttä
* [ ] Tarkasta että data tulee mukaan tulostusnäkymään oikealla kielellä

2023-11-06 14:03 UTC, oskarimysteerio submitted a review, later dismissed
Vaikutti toimivan ok, en itsekkään saanut toistettua tiedon katoamista - se varmaan vaatis jotain lisätietoa myöhemmin

2023-11-06 14:14 UTC, Alexander-Tallqvist-Siili commented
Testasin tätä myös. Vaikuttaa toimivan.

2023-11-07 05:07 UTC, jiisuominen requested changes
SonarCloud herjat vois ehkä fiksaa kans?

2023-11-07 06:58 UTC, Puavo commented
Yksi kohta korjattu, toisesta tehty tiketti: https://helsinkisolutionoffice.atlassian.net/browse/AU-1858

2023-11-16 07:56 UTC, jiisuominen approved these changes

2023-11-16 07:56 UTC, merged