fix: AU-1914: fix missing translations asukaspien
City-of-Helsinki/hel-fi-drupal-grants pull request #990
Opened 2023-11-27 13:07 UTC by strangeworlder

# [AU-1914](https://helsinkisolutionoffice.atlassian.net/browse/AU-1914)

## What was done

* Previous button fixed for fi/sv in Asukasosallisuus, pienavustushakemus

## How to install

* Make sure your instance is up and running on correct branch.
  * `git checkout feature/AU-1914-previous`
  * `make fresh`
* Run `make drush-cr`

## How to test

* [ ] Login as private person
* [ ] Go to [Asukasosallisuus, pienavustushakemus](https://hel-fi-drupal-grant-applications.docker.so/fi/uusi-hakemus/asukasosallisuus_pienavustushake)
* [ ] Go to preview page. See that the Previous button reads Edellinen, not Previous
* [ ] Switch to Swedish, check the above in Swedish as well.
* [ ] Check that code follows our standards

2023-11-27 13:28 UTC, suvikankare requested changes

2023-11-27 14:12 UTC, strangeworlder commented on conf/cmi/webform.webform.asukasosallisuus_pienavustushake.yml
> -      '#type': webform_actions
lisätty

2023-11-28 06:41 UTC, suvikankare requested changes

2023-11-28 06:41 UTC, suvikankare commented on public/modules/custom/grants_premises/templates/premises-composite-print.html.twig
Tän ei ehkä kuulu olla täällä?

2023-11-28 11:07 UTC, strangeworlder commented on public/modules/custom/grants_premises/templates/premises-composite-print.html.twig
No ei tosiaan.

2023-11-28 11:24 UTC, suvikankare approved these changes

2023-11-28 13:11 UTC, merged